{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "### Neovim version (nvim -v)\n\nv0.7.0-dev+861-g6ecaba510\n\n### Vim (not Nvim) behaves the same?\n\nno\n\n### Operating system/version\n\nDebian Unstable\n\n### Terminal name/version\n\nGNOME Terminal 3.42.2 using VTE 0.66.2 +BIDI +GNUTLS +ICU +SYSTEMD\n\n### $TERM environment variable\n\nxterm-256color\n\n### Installation\n\nbuild from repo\n\n### How to reproduce the issue\n\nDon't really know how to reproduce, it happens \"ramdomly\", but sometimes old LSP diagnostics will be kept on cache even after that was already solved.\r\n\r\nTwo examples here:\r\n![Screenshot from 2022-01-09 16-48-30](https://user-images.githubusercontent.com/134025/148702965-b82c829e-2e9d-4792-9830-bd74a563e5f6.png)\r\n\r\n![Screenshot from 2022-01-09 17-01-18](https://user-images.githubusercontent.com/134025/148702967-b9cd2569-1ddf-4695-bd0d-33c8e95966e1.png)\r\n\r\n(in this second case, note what the error is saying. It thinks the string there is different from what really is)\r\n\r\nIn both cases the problem was already fixed, but the issue is still being displayed, no matter how many times I save or even change that line.\r\n\r\nI tried inspecting `:lua print(vim.inspect(vim.diagnostic.get(0)))` and I can see that the diagnostics are still there in the cache. I even logged the `on_publish_diagnostics` and saw that the language server is really reporting those every time.\r\n\r\nAt first I thought it could be a problem with `pyright` specifically, but I saw that happening when editing my lua files too. Also, if I do a `:e`, the file gets parsed again and the issue goes away. The issue is also fixed if I delete the line and then insert it again (no need to save, just have to make it disappear and appear again)\r\n\r\nThat issue started happening some days ago (don't remember exactly when).\n\n### Expected behavior\n\nDescribed above.\n\n### Actual behavior\n\nDescribed above.",
    "closed_at": "2022-01-10T22:58:19Z",
    "comment_data": [
        {
            "author_association": "CONTRIBUTOR",
            "body": "Check `LspInfo` and ensure only one copy of the language server is running on the buffer, Make sure you are using the minimal config, and not lsp-installer, or some other lsp plugin.\r\n\r\nDiagnostics are only cleared when a subsequent round of diagnostics is sent from the language server. The cache is not updated incrementally but wiped per namespace on new diagnostics.",
            "created_at": "2022-01-09T22:20:35Z",
            "html_url": "https://github.com/neovim/neovim/issues/17017#issuecomment-1008435196",
            "id": 1008435196,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/17017",
            "node_id": "IC_kwDOAPphoM48G3_8",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1008435196/reactions"
            },
            "updated_at": "2022-01-09T22:24:42Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1008435196",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/13316262?v=4",
                "events_url": "https://api.github.com/users/mjlbach/events{/privacy}",
                "followers_url": "https://api.github.com/users/mjlbach/followers",
                "following_url": "https://api.github.com/users/mjlbach/following{/other_user}",
                "gists_url": "https://api.github.com/users/mjlbach/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/mjlbach",
                "id": 13316262,
                "login": "mjlbach",
                "node_id": "MDQ6VXNlcjEzMzE2MjYy",
                "organizations_url": "https://api.github.com/users/mjlbach/orgs",
                "received_events_url": "https://api.github.com/users/mjlbach/received_events",
                "repos_url": "https://api.github.com/users/mjlbach/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/mjlbach/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/mjlbach/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/mjlbach"
            }
        },
        {
            "author_association": "NONE",
            "body": "@mjlbach I checked `LspInfo` and there was only one there. I'll try to find a minimal config, but like I said, the issue happens very randomly to me, don't really know how to \"reproduce\" it... Sometimes it will take 2 minutes to happen, sometimes 30 minutes.\r\n\r\nAlso, note that the problem doesn't seem to be on diagnostic. Like i said, what is being displayed is really what was sent by `pyright`. I have a custom `\"textDocument/publishDiagnostics\"` implementation (https://github.com/bellini666/dotfiles/blob/master/vim/lua/config/lsp.lua#L22) that I use to remove HINTS from diagnostics and then I call the original func. I added a log to that function and I can see that pyright is really sending those \"non existing\" issues every time. So, for it to think that the line still looks like that, either it is a problem with it (I don't think so, because I saw something similar with lua language server), or neovim is failing to send some buffer update to it..\r\n\r\n",
            "created_at": "2022-01-09T22:29:17Z",
            "html_url": "https://github.com/neovim/neovim/issues/17017#issuecomment-1008436513",
            "id": 1008436513,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/17017",
            "node_id": "IC_kwDOAPphoM48G4Uh",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1008436513/reactions"
            },
            "updated_at": "2022-01-09T22:29:17Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1008436513",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/134025?v=4",
                "events_url": "https://api.github.com/users/bellini666/events{/privacy}",
                "followers_url": "https://api.github.com/users/bellini666/followers",
                "following_url": "https://api.github.com/users/bellini666/following{/other_user}",
                "gists_url": "https://api.github.com/users/bellini666/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/bellini666",
                "id": 134025,
                "login": "bellini666",
                "node_id": "MDQ6VXNlcjEzNDAyNQ==",
                "organizations_url": "https://api.github.com/users/bellini666/orgs",
                "received_events_url": "https://api.github.com/users/bellini666/received_events",
                "repos_url": "https://api.github.com/users/bellini666/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/bellini666/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/bellini666/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/bellini666"
            }
        },
        {
            "author_association": "NONE",
            "body": "Hey @mjlbach , here is a video showing the issue.\r\n\r\nhttps://user-images.githubusercontent.com/134025/148708473-4fbb4a6f-6d4c-4bd5-ad62-eb76e4407679.mp4\r\n\r\nAs you can see, the diagnostics is always changing, but for some reason it thinks there's an `u` at the end of that word, no matter how many times I delete and rewrite the line. What \"fixes\" the issue is when I make the line \"don't exist anymore\"  and make it \"exist again\" (with undo).\r\n\r\nedit: And one interesting thing. I saw the same happening with `flake8` using `null-ls`. It was reporting an error that didn't make sense anymore (like that one). But after doing any modification to the buffer, the issue was gone. That's probably because `null-ls` sends the whole buffer to `flake8` after any change, and that made it reread the whole thing.",
            "created_at": "2022-01-10T01:05:26Z",
            "html_url": "https://github.com/neovim/neovim/issues/17017#issuecomment-1008467164",
            "id": 1008467164,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/17017",
            "node_id": "IC_kwDOAPphoM48G_zc",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1008467164/reactions"
            },
            "updated_at": "2022-01-10T01:08:23Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1008467164",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/134025?v=4",
                "events_url": "https://api.github.com/users/bellini666/events{/privacy}",
                "followers_url": "https://api.github.com/users/bellini666/followers",
                "following_url": "https://api.github.com/users/bellini666/following{/other_user}",
                "gists_url": "https://api.github.com/users/bellini666/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/bellini666",
                "id": 134025,
                "login": "bellini666",
                "node_id": "MDQ6VXNlcjEzNDAyNQ==",
                "organizations_url": "https://api.github.com/users/bellini666/orgs",
                "received_events_url": "https://api.github.com/users/bellini666/received_events",
                "repos_url": "https://api.github.com/users/bellini666/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/bellini666/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/bellini666/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/bellini666"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "I need a minimum reproduction (the file that causes the issue reproduced with the minimal config) to do anything about this.",
            "created_at": "2022-01-10T01:41:58Z",
            "html_url": "https://github.com/neovim/neovim/issues/17017#issuecomment-1008481110",
            "id": 1008481110,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/17017",
            "node_id": "IC_kwDOAPphoM48HDNW",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1008481110/reactions"
            },
            "updated_at": "2022-01-10T01:41:58Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1008481110",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/13316262?v=4",
                "events_url": "https://api.github.com/users/mjlbach/events{/privacy}",
                "followers_url": "https://api.github.com/users/mjlbach/followers",
                "following_url": "https://api.github.com/users/mjlbach/following{/other_user}",
                "gists_url": "https://api.github.com/users/mjlbach/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/mjlbach",
                "id": 13316262,
                "login": "mjlbach",
                "node_id": "MDQ6VXNlcjEzMzE2MjYy",
                "organizations_url": "https://api.github.com/users/mjlbach/orgs",
                "received_events_url": "https://api.github.com/users/mjlbach/received_events",
                "repos_url": "https://api.github.com/users/mjlbach/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/mjlbach/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/mjlbach/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/mjlbach"
            }
        },
        {
            "author_association": "NONE",
            "body": "@mjlbach the problem is that I can't create a minimum reproduction example... The same file with the same contents and the same change doesn't always produce the issue. I'm still trying to find a way to reproduce it and I'll for sure get back here if I find a way.\r\n\r\nBut having said that, I just discovered the reason of the issue! I defined `vim.lsp.set_log_level(\"debug\")` and got it.\r\n\r\nWhen the error happened here I deleted the character 74 and saw this on the log:\r\n```\r\n[DEBUG][2022-01-10 00:17:41] .../vim/lsp/rpc.lua:347\t\"rpc.send\"\t{  jsonrpc = \"2.0\",  method = \"textDocument/didChange\",  params = {    contentChanges = { {        range = {          end = {            character = 73,            line = 32          },          start = {            character = 73,            line = 32          }        },        rangeLength = 0,        text = \")\"      } },    textDocument = {      uri = \"file:///home/bellini/dev/strawberry-django-plus/strawberry_django_plus/types.py\",      version = 1221    }  }}\r\n```\r\n\r\nAs you can see there, neovim is reporting to the language server that I changed the character 73 and not 74 (and that's why pyright still has \"trash\" in his internal buffer). After I deleted and created the line again to fix the issue, doing the same reported the line 74 correctly.\r\n\r\nI really don't know how to properly reproduce that (I'm trying). But maybe that can give a hint?",
            "created_at": "2022-01-10T03:23:53Z",
            "html_url": "https://github.com/neovim/neovim/issues/17017#issuecomment-1008513893",
            "id": 1008513893,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/17017",
            "node_id": "IC_kwDOAPphoM48HLNl",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1008513893/reactions"
            },
            "updated_at": "2022-01-10T03:24:37Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1008513893",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/134025?v=4",
                "events_url": "https://api.github.com/users/bellini666/events{/privacy}",
                "followers_url": "https://api.github.com/users/bellini666/followers",
                "following_url": "https://api.github.com/users/bellini666/following{/other_user}",
                "gists_url": "https://api.github.com/users/bellini666/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/bellini666",
                "id": 134025,
                "login": "bellini666",
                "node_id": "MDQ6VXNlcjEzNDAyNQ==",
                "organizations_url": "https://api.github.com/users/bellini666/orgs",
                "received_events_url": "https://api.github.com/users/bellini666/received_events",
                "repos_url": "https://api.github.com/users/bellini666/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/bellini666/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/bellini666/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/bellini666"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "Sounds like pyright is getting out of sync with neovim? Do you have any customizations around textDocument/didChange? Did this start recently? Perhaps you can try setting `debounce_text_changes` to 0 and see if that has any effect?",
            "created_at": "2022-01-10T03:45:25Z",
            "html_url": "https://github.com/neovim/neovim/issues/17017#issuecomment-1008519989",
            "id": 1008519989,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/17017",
            "node_id": "IC_kwDOAPphoM48HMs1",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1008519989/reactions"
            },
            "updated_at": "2022-01-10T03:45:25Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1008519989",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/108725?v=4",
                "events_url": "https://api.github.com/users/fsouza/events{/privacy}",
                "followers_url": "https://api.github.com/users/fsouza/followers",
                "following_url": "https://api.github.com/users/fsouza/following{/other_user}",
                "gists_url": "https://api.github.com/users/fsouza/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/fsouza",
                "id": 108725,
                "login": "fsouza",
                "node_id": "MDQ6VXNlcjEwODcyNQ==",
                "organizations_url": "https://api.github.com/users/fsouza/orgs",
                "received_events_url": "https://api.github.com/users/fsouza/received_events",
                "repos_url": "https://api.github.com/users/fsouza/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/fsouza/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/fsouza/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/fsouza"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "https://github.com/neovim/neovim/pull/17015/files may have fixed it, but I would be surprised as the scenario that PR addresses is extremely rare.",
            "created_at": "2022-01-10T16:35:11Z",
            "html_url": "https://github.com/neovim/neovim/issues/17017#issuecomment-1009076862",
            "id": 1009076862,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/17017",
            "node_id": "IC_kwDOAPphoM48JUp-",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1009076862/reactions"
            },
            "updated_at": "2022-01-10T16:35:11Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1009076862",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/13316262?v=4",
                "events_url": "https://api.github.com/users/mjlbach/events{/privacy}",
                "followers_url": "https://api.github.com/users/mjlbach/followers",
                "following_url": "https://api.github.com/users/mjlbach/following{/other_user}",
                "gists_url": "https://api.github.com/users/mjlbach/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/mjlbach",
                "id": 13316262,
                "login": "mjlbach",
                "node_id": "MDQ6VXNlcjEzMzE2MjYy",
                "organizations_url": "https://api.github.com/users/mjlbach/orgs",
                "received_events_url": "https://api.github.com/users/mjlbach/received_events",
                "repos_url": "https://api.github.com/users/mjlbach/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/mjlbach/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/mjlbach/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/mjlbach"
            }
        },
        {
            "author_association": "NONE",
            "body": "@fsouza no I do not have any customizations with `textDocument/didChange`, only [this one](https://github.com/bellini666/dotfiles/blob/master/vim/lua/config/lsp.lua#L26) for filtering hints out of diagnostics.\r\n\r\n@mjlbach tested it today and it seems to have fixed the issue for me for pyright. At least the pending change that never got flushed.\r\n\r\nI'm still seeing diagnostics from old buffer version though. With debounce set to 0 I pratically don't see it with pyright, but it happens with null-ls a lot. The next change to the buffer now fixes it, but it is an annoying issue.\r\n\r\nAlso, don't know if that is related, but sometimes the buffer seems to \"crash\" and the `BufWritePre` autocmd doesn't get called. This also started happening at the same time of this issue, but I thought they were related. Now I see that their causes might be different.\r\n\r\nMore specifically, I have a `autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync(nil, 1500)` that gets registered as soon as any lsp client gets attached. As I'm editing a file, when that \"crash\" happens (don't know what causes it), saving the file doesn't trigger the formatting anymore. I can see that null-ls is still working because it is still giving flake8 diagnostics, but the formatting function never gets called. Even more strange, if I do `:lua vim.lsp.buf.formatting_sync(nil, 1500)` by hand it works, which means that the lsp is still working fine, it is just that the autocmd is not being called at all.",
            "created_at": "2022-01-10T22:53:54Z",
            "html_url": "https://github.com/neovim/neovim/issues/17017#issuecomment-1009425610",
            "id": 1009425610,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/17017",
            "node_id": "IC_kwDOAPphoM48KpzK",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1009425610/reactions"
            },
            "updated_at": "2022-01-10T22:53:54Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1009425610",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/134025?v=4",
                "events_url": "https://api.github.com/users/bellini666/events{/privacy}",
                "followers_url": "https://api.github.com/users/bellini666/followers",
                "following_url": "https://api.github.com/users/bellini666/following{/other_user}",
                "gists_url": "https://api.github.com/users/bellini666/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/bellini666",
                "id": 134025,
                "login": "bellini666",
                "node_id": "MDQ6VXNlcjEzNDAyNQ==",
                "organizations_url": "https://api.github.com/users/bellini666/orgs",
                "received_events_url": "https://api.github.com/users/bellini666/received_events",
                "repos_url": "https://api.github.com/users/bellini666/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/bellini666/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/bellini666/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/bellini666"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "I don't see `update_in_insert=true` in your config. That might be it.\r\n\r\n> Also, don't know if that is related, but sometimes the buffer seems to \"crash\" and the BufWritePre autocmd doesn't get called. This also started happening at the same time of this issue, but I thought they were related. Now I see that their causes might be different.\r\n\r\nI'm not sure what crashing buffer means.\r\n\r\n> I'm still seeing diagnostics from old buffer version though. With debounce set to 0 I pratically don't see it with pyright, but it happens with null-ls a lot. \r\n\r\nYou can file an issue with null-ls, it's not a real language server and unsupported by neovim's built-in language server client as far as I'm concerned.\r\n\r\nIf you can reproduce any issues with pyright feel free to open another bug report with the reproduction.\r\n",
            "created_at": "2022-01-10T22:58:16Z",
            "html_url": "https://github.com/neovim/neovim/issues/17017#issuecomment-1009428432",
            "id": 1009428432,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/17017",
            "node_id": "IC_kwDOAPphoM48KqfQ",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1009428432/reactions"
            },
            "updated_at": "2022-01-10T22:58:42Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1009428432",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/13316262?v=4",
                "events_url": "https://api.github.com/users/mjlbach/events{/privacy}",
                "followers_url": "https://api.github.com/users/mjlbach/followers",
                "following_url": "https://api.github.com/users/mjlbach/following{/other_user}",
                "gists_url": "https://api.github.com/users/mjlbach/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/mjlbach",
                "id": 13316262,
                "login": "mjlbach",
                "node_id": "MDQ6VXNlcjEzMzE2MjYy",
                "organizations_url": "https://api.github.com/users/mjlbach/orgs",
                "received_events_url": "https://api.github.com/users/mjlbach/received_events",
                "repos_url": "https://api.github.com/users/mjlbach/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/mjlbach/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/mjlbach/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/mjlbach"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "@bellini666 perhaps check if the client isn't getting detached from the buffer (see https://neovim.discourse.group/t/prevent-detaching-lsp-clients/202). I think I ran into this issue last month during Advent of Code, but I haven't had a chance to revisit it since going back to work (guess who spends more time on Google Docs than neovim lol)\r\n\r\nIf you do run into that, it may be a good idea to continue the discussion on that discourse thread (unless you see a clear reproducer).\r\n\r\nI did run into a bug with efm where it wouldn't send the empty list diagnostics when there were no problems (https://github.com/mattn/efm-langserver/issues/197), but I assume null-ls doesn't have that issue.",
            "created_at": "2022-01-10T23:02:20Z",
            "html_url": "https://github.com/neovim/neovim/issues/17017#issuecomment-1009430514",
            "id": 1009430514,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/17017",
            "node_id": "IC_kwDOAPphoM48Kq_y",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1009430514/reactions"
            },
            "updated_at": "2022-01-10T23:02:20Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1009430514",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/108725?v=4",
                "events_url": "https://api.github.com/users/fsouza/events{/privacy}",
                "followers_url": "https://api.github.com/users/fsouza/followers",
                "following_url": "https://api.github.com/users/fsouza/following{/other_user}",
                "gists_url": "https://api.github.com/users/fsouza/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/fsouza",
                "id": 108725,
                "login": "fsouza",
                "node_id": "MDQ6VXNlcjEwODcyNQ==",
                "organizations_url": "https://api.github.com/users/fsouza/orgs",
                "received_events_url": "https://api.github.com/users/fsouza/received_events",
                "repos_url": "https://api.github.com/users/fsouza/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/fsouza/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/fsouza/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/fsouza"
            }
        },
        {
            "author_association": "NONE",
            "body": "> I don't see update_in_insert=true in your config. That might be it.\r\n\r\nI can see that issue in normal mode. I even try to save the file and it wont go away. I have to really trigger a change to the buffer (any chage) to send the updated buffer to the clients when that happens.\r\n\r\n> I'm not sure what crashing buffer means.\r\n\r\nDon't know how to properly describe it, sorry :(. There aren't any errors at my infobar, there aren't any errors at the log, but the autocommand doesn't seem to be working. Any idea of what might cause the `autocmd BufWritePre <buffer>` to stop working from one time to another? Because the function that it calls, `lua vim.lsp.buf.formatting_sync(nil, 1500)`, if I call by hand it still works, so what seems to not be working is the autocmd.\r\n\r\nAlso, since I think it is very unlikely for the `BufWritePre` to have stopped working, as it is a core event, my guess was that something happened to the `<buffer>`. I didn't unregister it and neither have closed the buffer or nothing like that. So, what might have caused that?\r\n\r\n> You can file an issue with null-ls, it's not a real language server and unsupported by neovim's built-in language server client as far as I'm concerned.\r\n\r\nI can surely do that... But the reason I'm saying it here is because after reading this line of how null-ls works (https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/diagnostics.lua#L138), I think what might be happening is that the old version is being sent (or if the version is empty, the changetick hasn't updated yet?). Does that make any sense? If not, I'm reporting this to null-ls.\r\n\r\n> @bellini666 perhaps check if the client isn't getting detached from the buffer (see https://neovim.discourse.group/t/prevent-detaching-lsp-clients/202). I think I ran into this issue last month during Advent of Code, but I haven't had a chance to revisit it since going back to work (guess who spends more time on Google Docs than neovim lol)\r\n\r\nI actually checked every time and the clients are not detached (btw, cheers from a brazilian \"irmão\" here too :) )\r\n\r\n> If you do run into that, it may be a good idea to continue the discussion on that discourse thread (unless you see a clear reproducer).\r\n\r\nI'll take a look at that thread and check if it has anything to do with my issues. Thanks for pointing that out :)",
            "created_at": "2022-01-10T23:40:20Z",
            "html_url": "https://github.com/neovim/neovim/issues/17017#issuecomment-1009460227",
            "id": 1009460227,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/17017",
            "node_id": "IC_kwDOAPphoM48KyQD",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1009460227/reactions"
            },
            "updated_at": "2022-01-10T23:40:20Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1009460227",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/134025?v=4",
                "events_url": "https://api.github.com/users/bellini666/events{/privacy}",
                "followers_url": "https://api.github.com/users/bellini666/followers",
                "following_url": "https://api.github.com/users/bellini666/following{/other_user}",
                "gists_url": "https://api.github.com/users/bellini666/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/bellini666",
                "id": 134025,
                "login": "bellini666",
                "node_id": "MDQ6VXNlcjEzNDAyNQ==",
                "organizations_url": "https://api.github.com/users/bellini666/orgs",
                "received_events_url": "https://api.github.com/users/bellini666/received_events",
                "repos_url": "https://api.github.com/users/bellini666/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/bellini666/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/bellini666/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/bellini666"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "> Don't know how to properly describe it, sorry :(. There aren't any errors at my infobar, there aren't any errors at the log, but the autocommand doesn't seem to be working. Any idea of what might cause the autocmd BufWritePre <buffer> to stop working from one time to another? Because the function that it calls, lua vim.lsp.buf.formatting_sync(nil, 1500), if I call by hand it still works, so what seems to not be working is the autocmd.\r\n\r\nnull-ls does weird things to inject itself as a language server, so I have no idea. I would file an issue with them. I strongly discourage plugins from pretending to be language servers. If you're having an issue with null-ls, you'll need to file a bug report with that plugin.",
            "created_at": "2022-01-11T00:25:22Z",
            "html_url": "https://github.com/neovim/neovim/issues/17017#issuecomment-1009481135",
            "id": 1009481135,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/17017",
            "node_id": "IC_kwDOAPphoM48K3Wv",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1009481135/reactions"
            },
            "updated_at": "2022-01-11T00:25:45Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1009481135",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/13316262?v=4",
                "events_url": "https://api.github.com/users/mjlbach/events{/privacy}",
                "followers_url": "https://api.github.com/users/mjlbach/followers",
                "following_url": "https://api.github.com/users/mjlbach/following{/other_user}",
                "gists_url": "https://api.github.com/users/mjlbach/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/mjlbach",
                "id": 13316262,
                "login": "mjlbach",
                "node_id": "MDQ6VXNlcjEzMzE2MjYy",
                "organizations_url": "https://api.github.com/users/mjlbach/orgs",
                "received_events_url": "https://api.github.com/users/mjlbach/received_events",
                "repos_url": "https://api.github.com/users/mjlbach/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/mjlbach/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/mjlbach/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/mjlbach"
            }
        },
        {
            "author_association": "NONE",
            "body": "@bellini666 did you ever find a proper solution for this? I'm having the exact same behavior with pyright configured through lspconfig. It happens very randomly, and running `:e` or restarting the LSP fixes it.",
            "created_at": "2024-06-21T15:41:43Z",
            "html_url": "https://github.com/neovim/neovim/issues/17017#issuecomment-2182994245",
            "id": 2182994245,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/17017",
            "node_id": "IC_kwDOAPphoM6CHdlF",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2182994245/reactions"
            },
            "updated_at": "2024-06-21T15:41:43Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2182994245",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/9911531?v=4",
                "events_url": "https://api.github.com/users/collindutter/events{/privacy}",
                "followers_url": "https://api.github.com/users/collindutter/followers",
                "following_url": "https://api.github.com/users/collindutter/following{/other_user}",
                "gists_url": "https://api.github.com/users/collindutter/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/collindutter",
                "id": 9911531,
                "login": "collindutter",
                "node_id": "MDQ6VXNlcjk5MTE1MzE=",
                "organizations_url": "https://api.github.com/users/collindutter/orgs",
                "received_events_url": "https://api.github.com/users/collindutter/received_events",
                "repos_url": "https://api.github.com/users/collindutter/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/collindutter/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/collindutter/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/collindutter"
            }
        },
        {
            "author_association": "NONE",
            "body": "> @bellini666 did you ever find a proper solution for this? I'm having the exact same behavior with pyright configured through lspconfig. It happens very randomly, and running `:e` or restarting the LSP fixes it.\r\n\r\nUnfortunately no. It happens randomly with pyright as well, although it has been less common to me lately. I'm running neovim from `HEAD` though\r\n\r\nAnd yes, when that happens, usually a `:e` or `:LspRestart` fixes the issue. But I have no idea on how to properly reproduce it to open a new issue here",
            "created_at": "2024-07-26T15:45:02Z",
            "html_url": "https://github.com/neovim/neovim/issues/17017#issuecomment-2253031494",
            "id": 2253031494,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/17017",
            "node_id": "IC_kwDOAPphoM6GSohG",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2253031494/reactions"
            },
            "updated_at": "2024-07-26T15:45:24Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2253031494",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/134025?v=4",
                "events_url": "https://api.github.com/users/bellini666/events{/privacy}",
                "followers_url": "https://api.github.com/users/bellini666/followers",
                "following_url": "https://api.github.com/users/bellini666/following{/other_user}",
                "gists_url": "https://api.github.com/users/bellini666/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/bellini666",
                "id": 134025,
                "login": "bellini666",
                "node_id": "MDQ6VXNlcjEzNDAyNQ==",
                "organizations_url": "https://api.github.com/users/bellini666/orgs",
                "received_events_url": "https://api.github.com/users/bellini666/received_events",
                "repos_url": "https://api.github.com/users/bellini666/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/bellini666/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/bellini666/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/bellini666"
            }
        }
    ],
    "comments": 14,
    "comments_url": "https://api.github.com/repos/neovim/neovim/issues/17017/comments",
    "created_at": "2022-01-09T22:15:55Z",
    "events_url": "https://api.github.com/repos/neovim/neovim/issues/17017/events",
    "html_url": "https://github.com/neovim/neovim/issues/17017",
    "id": 1097316713,
    "labels": [
        {
            "color": "f9d0c4",
            "default": true,
            "description": "issues reporting wrong behavior",
            "id": 77997474,
            "name": "bug",
            "node_id": "MDU6TGFiZWw3Nzk5NzQ3NA==",
            "url": "https://api.github.com/repos/neovim/neovim/labels/bug"
        },
        {
            "color": "c5def5",
            "default": false,
            "description": null,
            "id": 662566370,
            "name": "lsp",
            "node_id": "MDU6TGFiZWw2NjI1NjYzNzA=",
            "url": "https://api.github.com/repos/neovim/neovim/labels/lsp"
        },
        {
            "color": "C5DEF5",
            "default": false,
            "description": "",
            "id": 3361645105,
            "name": "diagnostic",
            "node_id": "MDU6TGFiZWwzMzYxNjQ1MTA1",
            "url": "https://api.github.com/repos/neovim/neovim/labels/diagnostic"
        }
    ],
    "labels_url": "https://api.github.com/repos/neovim/neovim/issues/17017/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOAPphoM5BZ7lp",
    "number": 17017,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 5,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 5,
        "url": "https://api.github.com/repos/neovim/neovim/issues/17017/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/neovim",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/neovim/neovim/issues/17017/timeline",
    "title": "LSP Diagnostics sometimes not being cleared",
    "updated_at": "2024-07-26T15:45:25Z",
    "url": "https://api.github.com/repos/neovim/neovim/issues/17017",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/134025?v=4",
        "events_url": "https://api.github.com/users/bellini666/events{/privacy}",
        "followers_url": "https://api.github.com/users/bellini666/followers",
        "following_url": "https://api.github.com/users/bellini666/following{/other_user}",
        "gists_url": "https://api.github.com/users/bellini666/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/bellini666",
        "id": 134025,
        "login": "bellini666",
        "node_id": "MDQ6VXNlcjEzNDAyNQ==",
        "organizations_url": "https://api.github.com/users/bellini666/orgs",
        "received_events_url": "https://api.github.com/users/bellini666/received_events",
        "repos_url": "https://api.github.com/users/bellini666/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/bellini666/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/bellini666/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/bellini666"
    }
}