{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "### Describe the bug\r\n\r\nI am not able to get neovim to detect python 3 on Windows 11 pro. I made several attempts.\r\n\r\n1)\r\n- installed python 3.10 (and also 3.7 after uninstalling 3.10) from the Microsoft Store\r\n- installed neovim 0.8.2 via chocolatey\r\n- followed the guide https://neovim.io/doc/user/provider.html + stackoverlow question and answers. I am sure I used correct path, keys, etc.\r\n\r\nnvim has never detected a python provider able to import neovim (tested within several shells)\r\n\r\n2)\r\n- uninstalled python got via the MS app store\r\n- installed python 3.11 via chocolatey\r\nsame results sa above.\r\n\r\nEvery time I ran `:checkhealth` and got this:\r\n```\r\n## Python 3 provider (optional)\r\n  - INFO: Using: g:python3_host_prog = \"C:/Python311/python.exe\"\r\n  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.\r\n  - INFO: Executable: Not found\r\n\r\n## Python virtualenv\r\n  - OK: no $VIRTUAL_ENV\r\n```\r\nThis last message corresponds to the attempt with choco installation.\r\n\r\nBut then I can:\r\n```\r\nC:\\>python --version\r\nPython 3.11.0\r\n\r\nC:\\>python\r\nPython 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)] on win32\r\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\r\n>>> import neovim\r\n>>> import pynvim\r\n>>> print(neovim.__file__)\r\nC:\\Users\\user\\AppData\\Roaming\\Python\\Python311\\site-packages\\neovim\\__init__.py\r\n>>> print(pynvim.__file__)\r\nC:\\Users\\user\\AppData\\Roaming\\Python\\Python311\\site-packages\\pynvim\\__init__.py\r\n```\r\n\r\nNOTE:  In all cases I also uninstalled and reinstalled neovim via chocolatey. I tried to specify the path with /, \\\\, etc. single quotes double quotes. I think I did not leave anything untested.\r\n\r\nIn ALL cases, in all shells I could just execute `python` and `import neovim` or `import pynvim` without issues (as shown above)\r\n\r\nIf neovim on windows is supposed to detect python, I think there is a bug somewhere.\r\n\r\n\r\n\r\n\r\n### Steps to reproduce\r\n\r\nDescribed above. Basically follow the instructions to use python with neovim.\r\n\r\n### Expected behavior\r\n\r\nI would expect neovim to detect the python provider\r\n\r\n\r\n### Neovim version (nvim -v)\r\n\r\n0.8.3\r\n\r\n### Vim (not Nvim) behaves the same?\r\n\r\nnot installed\r\n\r\n### Operating system/version\r\n\r\nWindows 11\r\n\r\n### Terminal name/version\r\n\r\nWindows Terminal, git bash, command promp, powershell\r\n\r\n### $TERM environment variable\r\n\r\nnone\r\n\r\n### Installation\r\n\r\nchoco / windows store",
    "closed_at": "2023-02-15T14:01:29Z",
    "comment_data": [
        {
            "author_association": "NONE",
            "body": "Neovim doesn't detect python (for me, should it?), but you can set it explicitly by setting `g:python3_host_prog` in your Lua configuration as it says in the `:checkhealth` output. So this is probably not a bug, please read `:h g:python3_host_prog` or [make a Google search](https://www.google.com/search?q=g%3Apython3_host_prog).",
            "created_at": "2023-02-04T16:16:20Z",
            "html_url": "https://github.com/neovim/neovim/issues/22117#issuecomment-1416791950",
            "id": 1416791950,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/22117",
            "node_id": "IC_kwDOAPphoM5UcoeO",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1416791950/reactions"
            },
            "updated_at": "2023-02-04T16:17:47Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1416791950",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/24259245?v=4",
                "events_url": "https://api.github.com/users/martin-braun/events{/privacy}",
                "followers_url": "https://api.github.com/users/martin-braun/followers",
                "following_url": "https://api.github.com/users/martin-braun/following{/other_user}",
                "gists_url": "https://api.github.com/users/martin-braun/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/martin-braun",
                "id": 24259245,
                "login": "martin-braun",
                "node_id": "MDQ6VXNlcjI0MjU5MjQ1",
                "organizations_url": "https://api.github.com/users/martin-braun/orgs",
                "received_events_url": "https://api.github.com/users/martin-braun/received_events",
                "repos_url": "https://api.github.com/users/martin-braun/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/martin-braun/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/martin-braun/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/martin-braun"
            }
        },
        {
            "author_association": "NONE",
            "body": "I did, it was in the output of `:checkhealth()` (see above):\r\n```\r\nINFO: Using: g:python3_host_prog = \"C:/Python311/python.exe\"\r\n```\r\ni.e., where chocolatey installed it.\r\n\r\n As I said, I followed all the instructions.",
            "created_at": "2023-02-04T17:00:07Z",
            "html_url": "https://github.com/neovim/neovim/issues/22117#issuecomment-1416800342",
            "id": 1416800342,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/22117",
            "node_id": "IC_kwDOAPphoM5UcqhW",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1416800342/reactions"
            },
            "updated_at": "2023-02-04T17:02:45Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1416800342",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/6717655?v=4",
                "events_url": "https://api.github.com/users/thistlillo/events{/privacy}",
                "followers_url": "https://api.github.com/users/thistlillo/followers",
                "following_url": "https://api.github.com/users/thistlillo/following{/other_user}",
                "gists_url": "https://api.github.com/users/thistlillo/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/thistlillo",
                "id": 6717655,
                "login": "thistlillo",
                "node_id": "MDQ6VXNlcjY3MTc2NTU=",
                "organizations_url": "https://api.github.com/users/thistlillo/orgs",
                "received_events_url": "https://api.github.com/users/thistlillo/received_events",
                "repos_url": "https://api.github.com/users/thistlillo/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/thistlillo/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/thistlillo/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/thistlillo"
            }
        },
        {
            "author_association": "NONE",
            "body": "Have you installed the [Neovim provider for Python](https://pypi.org/project/neovim/)? `pip install neovim`",
            "created_at": "2023-02-04T19:21:31Z",
            "html_url": "https://github.com/neovim/neovim/issues/22117#issuecomment-1416830701",
            "id": 1416830701,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/22117",
            "node_id": "IC_kwDOAPphoM5Ucx7t",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1416830701/reactions"
            },
            "updated_at": "2023-02-04T19:21:31Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1416830701",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/24259245?v=4",
                "events_url": "https://api.github.com/users/martin-braun/events{/privacy}",
                "followers_url": "https://api.github.com/users/martin-braun/followers",
                "following_url": "https://api.github.com/users/martin-braun/following{/other_user}",
                "gists_url": "https://api.github.com/users/martin-braun/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/martin-braun",
                "id": 24259245,
                "login": "martin-braun",
                "node_id": "MDQ6VXNlcjI0MjU5MjQ1",
                "organizations_url": "https://api.github.com/users/martin-braun/orgs",
                "received_events_url": "https://api.github.com/users/martin-braun/received_events",
                "repos_url": "https://api.github.com/users/martin-braun/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/martin-braun/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/martin-braun/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/martin-braun"
            }
        },
        {
            "author_association": "NONE",
            "body": "Yes, I did.\r\n\r\n```\r\nC:\\>python\r\nPython 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)] on win32\r\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\r\n>>> import neovim\r\n>>> import pynvim\r\n>>> print(neovim.__file__)\r\nC:\\Users\\user\\AppData\\Roaming\\Python\\Python311\\site-packages\\neovim\\__init__.py\r\n>>> print(pynvim.__file__)\r\nC:\\Users\\user\\AppData\\Roaming\\Python\\Python311\\site-packages\\pynvim\\__init__.py\r\n```\r\n\r\nHowever, yesterday night I ended up uninstalling everything. I will make another attempt over the next weekends. In my initial message I did not show the content of `C:/Python311/` but I can assure you it was the correct path, `python.exe` was there.",
            "created_at": "2023-02-05T06:19:54Z",
            "html_url": "https://github.com/neovim/neovim/issues/22117#issuecomment-1416933063",
            "id": 1416933063,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/22117",
            "node_id": "IC_kwDOAPphoM5UdK7H",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1416933063/reactions"
            },
            "updated_at": "2023-02-05T06:28:03Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1416933063",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/6717655?v=4",
                "events_url": "https://api.github.com/users/thistlillo/events{/privacy}",
                "followers_url": "https://api.github.com/users/thistlillo/followers",
                "following_url": "https://api.github.com/users/thistlillo/following{/other_user}",
                "gists_url": "https://api.github.com/users/thistlillo/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/thistlillo",
                "id": 6717655,
                "login": "thistlillo",
                "node_id": "MDQ6VXNlcjY3MTc2NTU=",
                "organizations_url": "https://api.github.com/users/thistlillo/orgs",
                "received_events_url": "https://api.github.com/users/thistlillo/received_events",
                "repos_url": "https://api.github.com/users/thistlillo/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/thistlillo/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/thistlillo/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/thistlillo"
            }
        },
        {
            "author_association": "NONE",
            "body": "@thistlillo If it doesn't work in the next attempt, you can always try to troubleshoot within Neovim by doing `:! command` as if you were in your normal Windows Prompt.",
            "created_at": "2023-02-05T22:45:17Z",
            "html_url": "https://github.com/neovim/neovim/issues/22117#issuecomment-1418285664",
            "id": 1418285664,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/22117",
            "node_id": "IC_kwDOAPphoM5UiVJg",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1418285664/reactions"
            },
            "updated_at": "2023-02-05T22:45:17Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1418285664",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/24259245?v=4",
                "events_url": "https://api.github.com/users/martin-braun/events{/privacy}",
                "followers_url": "https://api.github.com/users/martin-braun/followers",
                "following_url": "https://api.github.com/users/martin-braun/following{/other_user}",
                "gists_url": "https://api.github.com/users/martin-braun/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/martin-braun",
                "id": 24259245,
                "login": "martin-braun",
                "node_id": "MDQ6VXNlcjI0MjU5MjQ1",
                "organizations_url": "https://api.github.com/users/martin-braun/orgs",
                "received_events_url": "https://api.github.com/users/martin-braun/received_events",
                "repos_url": "https://api.github.com/users/martin-braun/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/martin-braun/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/martin-braun/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/martin-braun"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "I cannot reproduce this bug.  Should be closed.  OP can re-open if they still experience it.",
            "created_at": "2023-02-15T13:21:08Z",
            "html_url": "https://github.com/neovim/neovim/issues/22117#issuecomment-1431361378",
            "id": 1431361378,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/22117",
            "node_id": "IC_kwDOAPphoM5VUNdi",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1431361378/reactions"
            },
            "updated_at": "2023-02-15T13:21:08Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1431361378",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/32037751?v=4",
                "events_url": "https://api.github.com/users/3N4N/events{/privacy}",
                "followers_url": "https://api.github.com/users/3N4N/followers",
                "following_url": "https://api.github.com/users/3N4N/following{/other_user}",
                "gists_url": "https://api.github.com/users/3N4N/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/3N4N",
                "id": 32037751,
                "login": "3N4N",
                "node_id": "MDQ6VXNlcjMyMDM3NzUx",
                "organizations_url": "https://api.github.com/users/3N4N/orgs",
                "received_events_url": "https://api.github.com/users/3N4N/received_events",
                "repos_url": "https://api.github.com/users/3N4N/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/3N4N/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/3N4N/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/3N4N"
            }
        },
        {
            "author_association": "NONE",
            "body": "Sorry, but I have not tried again. I will keep you updated.",
            "created_at": "2023-02-15T21:26:58Z",
            "html_url": "https://github.com/neovim/neovim/issues/22117#issuecomment-1432055997",
            "id": 1432055997,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/22117",
            "node_id": "IC_kwDOAPphoM5VW3C9",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1432055997/reactions"
            },
            "updated_at": "2023-02-15T21:26:58Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1432055997",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/6717655?v=4",
                "events_url": "https://api.github.com/users/thistlillo/events{/privacy}",
                "followers_url": "https://api.github.com/users/thistlillo/followers",
                "following_url": "https://api.github.com/users/thistlillo/following{/other_user}",
                "gists_url": "https://api.github.com/users/thistlillo/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/thistlillo",
                "id": 6717655,
                "login": "thistlillo",
                "node_id": "MDQ6VXNlcjY3MTc2NTU=",
                "organizations_url": "https://api.github.com/users/thistlillo/orgs",
                "received_events_url": "https://api.github.com/users/thistlillo/received_events",
                "repos_url": "https://api.github.com/users/thistlillo/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/thistlillo/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/thistlillo/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/thistlillo"
            }
        },
        {
            "author_association": "NONE",
            "body": "For the following friends who might have the same problem and find this post:\r\nI followed exactly all the steps I should, but the problem was still there. \r\n\r\nWindows 11\r\nPython: 3.11\r\npynvim: 0.4.3\r\nnvim: 0.9\r\n\r\nI have the problem fixed by installing my python through the [official site](https://www.python.org/downloads/). Before I installed through installers like Microsoft store, tried different versions of python, not working.",
            "created_at": "2023-05-11T21:55:02Z",
            "html_url": "https://github.com/neovim/neovim/issues/22117#issuecomment-1544736111",
            "id": 1544736111,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/22117",
            "node_id": "IC_kwDOAPphoM5cEs1v",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 1,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1544736111/reactions"
            },
            "updated_at": "2023-05-11T21:55:02Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1544736111",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/34515663?v=4",
                "events_url": "https://api.github.com/users/resort09/events{/privacy}",
                "followers_url": "https://api.github.com/users/resort09/followers",
                "following_url": "https://api.github.com/users/resort09/following{/other_user}",
                "gists_url": "https://api.github.com/users/resort09/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/resort09",
                "id": 34515663,
                "login": "resort09",
                "node_id": "MDQ6VXNlcjM0NTE1NjYz",
                "organizations_url": "https://api.github.com/users/resort09/orgs",
                "received_events_url": "https://api.github.com/users/resort09/received_events",
                "repos_url": "https://api.github.com/users/resort09/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/resort09/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/resort09/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/resort09"
            }
        },
        {
            "author_association": "NONE",
            "body": "The same problem:\r\n\r\nPython 3 provider (optional)\r\n- WARNING No Python executable found that can `import neovim`. Using the first available executable for diagnostics.\r\n- WARNING Could not load Python 3:\r\n  python3 not found in search path or not executable.\r\n  python3.10 not found in search path or not executable.\r\n  python3.9 not found in search path or not executable.\r\n  python3.8 not found in search path or not executable.\r\n  python3.7 not found in search path or not executable.\r\n  python not found in search path or not executable.\r\n  - ADVICE:\r\n    - See :help provider-python for more information.\r\n    - You may disable this provider (and warning) by adding let g:loaded_python3_provider = 0 to your init.vim\r\n- Executable: Not found\r\n\r\nPython3 is in path an can be started from the same CMD window where Nvim has been started\r\n\r\nWindows11\r\nPuthon 3.11 from Microsoft Store",
            "created_at": "2023-11-21T09:13:11Z",
            "html_url": "https://github.com/neovim/neovim/issues/22117#issuecomment-1820516215",
            "id": 1820516215,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/22117",
            "node_id": "IC_kwDOAPphoM5sgt93",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1820516215/reactions"
            },
            "updated_at": "2023-11-21T14:37:12Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1820516215",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/11873804?v=4",
                "events_url": "https://api.github.com/users/KarlikB/events{/privacy}",
                "followers_url": "https://api.github.com/users/KarlikB/followers",
                "following_url": "https://api.github.com/users/KarlikB/following{/other_user}",
                "gists_url": "https://api.github.com/users/KarlikB/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/KarlikB",
                "id": 11873804,
                "login": "KarlikB",
                "node_id": "MDQ6VXNlcjExODczODA0",
                "organizations_url": "https://api.github.com/users/KarlikB/orgs",
                "received_events_url": "https://api.github.com/users/KarlikB/received_events",
                "repos_url": "https://api.github.com/users/KarlikB/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/KarlikB/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/KarlikB/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/KarlikB"
            }
        },
        {
            "author_association": "NONE",
            "body": "I had the same issue. Python was installed. `python` in the CLI worked, but neovim could not detect python, even when explicitly pointed to the path.\r\nThe problem was the version of python from the microsoft store.\r\nInstalling python directly from https://www.python.org/downloads/ and pointing neovim to that install using `g:python3_host_prog` resolved the issue.",
            "created_at": "2024-03-02T03:32:45Z",
            "html_url": "https://github.com/neovim/neovim/issues/22117#issuecomment-1974253245",
            "id": 1974253245,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/22117",
            "node_id": "IC_kwDOAPphoM51rLa9",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1974253245/reactions"
            },
            "updated_at": "2024-03-02T03:32:45Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1974253245",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/4077188?v=4",
                "events_url": "https://api.github.com/users/dylanrenwick/events{/privacy}",
                "followers_url": "https://api.github.com/users/dylanrenwick/followers",
                "following_url": "https://api.github.com/users/dylanrenwick/following{/other_user}",
                "gists_url": "https://api.github.com/users/dylanrenwick/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/dylanrenwick",
                "id": 4077188,
                "login": "dylanrenwick",
                "node_id": "MDQ6VXNlcjQwNzcxODg=",
                "organizations_url": "https://api.github.com/users/dylanrenwick/orgs",
                "received_events_url": "https://api.github.com/users/dylanrenwick/received_events",
                "repos_url": "https://api.github.com/users/dylanrenwick/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/dylanrenwick/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/dylanrenwick/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/dylanrenwick"
            }
        }
    ],
    "comments": 10,
    "comments_url": "https://api.github.com/repos/neovim/neovim/issues/22117/comments",
    "created_at": "2023-02-04T14:01:45Z",
    "events_url": "https://api.github.com/repos/neovim/neovim/issues/22117/events",
    "html_url": "https://github.com/neovim/neovim/issues/22117",
    "id": 1570956169,
    "labels": [
        {
            "color": "f9d0c4",
            "default": true,
            "description": "issues reporting wrong behavior",
            "id": 77997474,
            "name": "bug",
            "node_id": "MDU6TGFiZWw3Nzk5NzQ3NA==",
            "url": "https://api.github.com/repos/neovim/neovim/labels/bug"
        },
        {
            "color": "d4c5f9",
            "default": false,
            "description": null,
            "id": 109461219,
            "name": "platform:windows",
            "node_id": "MDU6TGFiZWwxMDk0NjEyMTk=",
            "url": "https://api.github.com/repos/neovim/neovim/labels/platform:windows"
        },
        {
            "color": "c5def5",
            "default": false,
            "description": null,
            "id": 144672485,
            "name": "provider",
            "node_id": "MDU6TGFiZWwxNDQ2NzI0ODU=",
            "url": "https://api.github.com/repos/neovim/neovim/labels/provider"
        }
    ],
    "labels_url": "https://api.github.com/repos/neovim/neovim/issues/22117/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOAPphoM5douOJ",
    "number": 22117,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/neovim/neovim/issues/22117/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/neovim",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/neovim/neovim/issues/22117/timeline",
    "title": "neovim does not detect python on Windows 11",
    "updated_at": "2024-03-02T03:32:47Z",
    "url": "https://api.github.com/repos/neovim/neovim/issues/22117",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/6717655?v=4",
        "events_url": "https://api.github.com/users/thistlillo/events{/privacy}",
        "followers_url": "https://api.github.com/users/thistlillo/followers",
        "following_url": "https://api.github.com/users/thistlillo/following{/other_user}",
        "gists_url": "https://api.github.com/users/thistlillo/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/thistlillo",
        "id": 6717655,
        "login": "thistlillo",
        "node_id": "MDQ6VXNlcjY3MTc2NTU=",
        "organizations_url": "https://api.github.com/users/thistlillo/orgs",
        "received_events_url": "https://api.github.com/users/thistlillo/received_events",
        "repos_url": "https://api.github.com/users/thistlillo/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/thistlillo/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/thistlillo/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/thistlillo"
    }
}