{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "CONTRIBUTOR",
    "body": "### Problem\n\nI'm not sure if this is a problem only with pylsp.pylint diagnostic or a general problem.\r\n\r\nFrom this state\r\n```py\r\nI      ■ [missing-module-docstring] Missing module docstring\r\n\r\nI def foo():     ■ [disallowed-name] Disallowed name \"foo\"\r\n      pass\r\n``` \r\nBy entering insert mode and adding a newline and then exit insert mode. the diagnostics will update to look like below:\r\n```py\r\nI      ■ [missing-module-docstring] Missing module docstring\r\n\r\nI      ■ [disallowed-name] Disallowed name \"foo\"\r\nW def foo():     ■ E303 too many blank lines (3)\r\n      pass\r\n```\r\n\r\nAs you can see the `[disallowed-name]` diagnostic from pylint is on the wrong line now. Also if the cursor is on this line and we try to execute `lua vim.diagnostic.goto_prev()`, nothing will happen.\n\n### Steps to reproduce\n\nconfig:\r\n\r\n```vim\r\nPlug 'neovim/nvim-lspconfig'\r\nlua local lsp = require('lspconfig')\r\nlua lsp.pylsp.setup { settings = { pylsp = { plugins = { pylint = { enabled = true }}}}}\r\n```\n\n### Expected behavior\n\ngoto_prev to not \"hang\" even if the diagnostic position is incorrect\n\n### Neovim version (nvim -v)\n\n0.9.4\n\n### Vim (not Nvim) behaves the same?\n\nN/A?\n\n### Operating system/version\n\nUbuntu 22.04\n\n### Terminal name/version\n\nwezterm over ssh\n\n### $TERM environment variable\n\nxterm-256color\n\n### Installation\n\ndownload and unpack linux64 tar.gz release",
    "closed_at": null,
    "comment_data": [],
    "comments": 0,
    "comments_url": "https://api.github.com/repos/neovim/neovim/issues/26079/comments",
    "created_at": "2023-11-16T23:09:44Z",
    "events_url": "https://api.github.com/repos/neovim/neovim/issues/26079/events",
    "html_url": "https://github.com/neovim/neovim/issues/26079",
    "id": 1997944893,
    "labels": [
        {
            "color": "f9d0c4",
            "default": true,
            "description": "issues reporting wrong behavior",
            "id": 77997474,
            "name": "bug",
            "node_id": "MDU6TGFiZWw3Nzk5NzQ3NA==",
            "url": "https://api.github.com/repos/neovim/neovim/labels/bug"
        },
        {
            "color": "c5def5",
            "default": false,
            "description": null,
            "id": 662566370,
            "name": "lsp",
            "node_id": "MDU6TGFiZWw2NjI1NjYzNzA=",
            "url": "https://api.github.com/repos/neovim/neovim/labels/lsp"
        }
    ],
    "labels_url": "https://api.github.com/repos/neovim/neovim/issues/26079/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOAPphoM53Fjg9",
    "number": 26079,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/neovim/neovim/issues/26079/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/neovim",
    "state": "open",
    "state_reason": null,
    "timeline_url": "https://api.github.com/repos/neovim/neovim/issues/26079/timeline",
    "title": "When lsp diagnostics are on wrong line, goto_prev stops working",
    "updated_at": "2023-11-16T23:09:54Z",
    "url": "https://api.github.com/repos/neovim/neovim/issues/26079",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/4508793?v=4",
        "events_url": "https://api.github.com/users/kaddkaka/events{/privacy}",
        "followers_url": "https://api.github.com/users/kaddkaka/followers",
        "following_url": "https://api.github.com/users/kaddkaka/following{/other_user}",
        "gists_url": "https://api.github.com/users/kaddkaka/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/kaddkaka",
        "id": 4508793,
        "login": "kaddkaka",
        "node_id": "MDQ6VXNlcjQ1MDg3OTM=",
        "organizations_url": "https://api.github.com/users/kaddkaka/orgs",
        "received_events_url": "https://api.github.com/users/kaddkaka/received_events",
        "repos_url": "https://api.github.com/users/kaddkaka/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/kaddkaka/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kaddkaka/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/kaddkaka"
    }
}