{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "### Problem\r\n\r\nI followed all the build instructions from the BUILD.md and I have all the required deps.\r\nI haven't changed anything on any of the files after git clone and I even ran and removed the previous nvim version;\r\n```sh\r\nsudo rm -f /usr/local/bin/nvim && sudo rm -rf /usr/local/share/nvim\r\n```\r\n\r\nhowever; after running the final step in the build step: sudo make install\r\nI open nvim only to be greeted by an error message:\r\n\r\n**E484: Can't open file /usr/local/share/nvim/syntax/syntax.vim**\r\n\r\nwhen I run: **echo $VIMRUNTIME**\r\ninside nvim I get: **/usr/local/share/nvim**\r\n\r\nit seems that nvim is looking for **/usr/local/share/nvim/syntax/syntax.vim** but the real path of syntax.vim is: **/usr/local/share/nvim/runtime/syntax/syntax.vim**\r\n\r\nI'm not sure what I did wrong as I followed all the steps as they were in BUILD.md. \r\n\r\nI have already tried to make distclean, delete previous nvim and reinstall nvim and no matter what I do I get the same error after I open nvim.\r\n\r\nIf anybody could please help me or point me in the right direction, I would highly appreciate it.\r\n\r\n### Steps to reproduce\r\n\r\n```sh\r\nsudo rm -f /usr/local/bin/nvim && sudo rm -rf /usr/local/share/nvim\r\n```\r\n\r\nThen:\r\n```sh\r\ncd neovim/ && make distclean\r\n```\r\n\r\nAfterwards:\r\n```sh\r\nmake CMAKE_BUILD_TYPE=RelWithDebInfo\r\n```\r\nFinally:\r\n```sh\r\nsudo make install\r\n```\r\nIt builds successfully but upon opening nvim:\r\nE484: Can't open file /usr/local/share/nvim/syntax/syntax.vim\r\n\r\n\r\n### Expected behavior\r\n\r\nnvim opens with no error messages.\r\n\r\n### Neovim version (nvim -v)\r\n\r\nnvim v0.10.0-dev-2039+g583c1de17\r\n\r\n### Vim (not Nvim) behaves the same?\r\n\r\nno\r\n\r\n### Operating system/version\r\n\r\nArch Linux x86_64\r\n\r\n### Terminal name/version\r\n\r\nalacritty 0.13.0\r\n\r\n### $TERM environment variable\r\n\r\nxterm-256color\r\n\r\n### Installation\r\n\r\nbuilt from source",
    "closed_at": "2024-01-11T23:51:56Z",
    "comment_data": [
        {
            "author_association": "MEMBER",
            "body": "> when I run: echo $VIMRUNTIME\r\n> inside nvim I get: /usr/local/share/nvim\r\n\r\nThat is incorrect; it should be `/usr/local/share/nvim/runtime`.\r\n\r\nDo you have write permissions on `/usr/local`?",
            "created_at": "2024-01-05T19:22:57Z",
            "html_url": "https://github.com/neovim/neovim/issues/26906#issuecomment-1879155570",
            "id": 1879155570,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/26906",
            "node_id": "IC_kwDOAPphoM5wAaNy",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1879155570/reactions"
            },
            "updated_at": "2024-01-05T19:22:57Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1879155570",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/2361214?v=4",
                "events_url": "https://api.github.com/users/clason/events{/privacy}",
                "followers_url": "https://api.github.com/users/clason/followers",
                "following_url": "https://api.github.com/users/clason/following{/other_user}",
                "gists_url": "https://api.github.com/users/clason/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/clason",
                "id": 2361214,
                "login": "clason",
                "node_id": "MDQ6VXNlcjIzNjEyMTQ=",
                "organizations_url": "https://api.github.com/users/clason/orgs",
                "received_events_url": "https://api.github.com/users/clason/received_events",
                "repos_url": "https://api.github.com/users/clason/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/clason/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/clason/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/clason"
            }
        },
        {
            "author_association": "NONE",
            "body": "> > when I run: echo $VIMRUNTIME\r\n> > inside nvim I get: /usr/local/share/nvim\r\n> \r\n> That is incorrect; it should be `/usr/local/share/nvim/runtime`.\r\n> \r\n> Do you have write permissions on `/usr/local`?\r\n\r\nI do not. I'm on a fresh install of Arch. I thought it was normal to not have write permission to **/usr/local/** as that path should only have read permission? \r\n\r\nAm I wrong? if so, how do I fix it? \r\nThank you for the timely reply.",
            "created_at": "2024-01-05T19:28:37Z",
            "html_url": "https://github.com/neovim/neovim/issues/26906#issuecomment-1879161362",
            "id": 1879161362,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/26906",
            "node_id": "IC_kwDOAPphoM5wAboS",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1879161362/reactions"
            },
            "updated_at": "2024-01-05T19:28:37Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1879161362",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/87588457?v=4",
                "events_url": "https://api.github.com/users/khezerberg/events{/privacy}",
                "followers_url": "https://api.github.com/users/khezerberg/followers",
                "following_url": "https://api.github.com/users/khezerberg/following{/other_user}",
                "gists_url": "https://api.github.com/users/khezerberg/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/khezerberg",
                "id": 87588457,
                "login": "khezerberg",
                "node_id": "MDQ6VXNlcjg3NTg4NDU3",
                "organizations_url": "https://api.github.com/users/khezerberg/orgs",
                "received_events_url": "https://api.github.com/users/khezerberg/received_events",
                "repos_url": "https://api.github.com/users/khezerberg/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/khezerberg/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/khezerberg/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/khezerberg"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Is there any other config in your shell in your nvim config that sets `$VIMRUNTIME`? That's sounds very strange that `$VIMRUNTIME` points to a wrong directory even if you did a clean-install.\r\n\r\nIn your shell, please try:\r\n\r\n```bash\r\nenv | grep VIM\r\n\r\nbash -c 'echo $VIMRUNTIME'\r\n\r\nnvim --clean --headless -c 'echo $VIMRUNTIME' -c 'q'\r\n```\r\n",
            "created_at": "2024-01-06T20:31:20Z",
            "html_url": "https://github.com/neovim/neovim/issues/26906#issuecomment-1879820744",
            "id": 1879820744,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/26906",
            "node_id": "IC_kwDOAPphoM5wC8nI",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1879820744/reactions"
            },
            "updated_at": "2024-01-06T20:31:53Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1879820744",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1009873?v=4",
                "events_url": "https://api.github.com/users/wookayin/events{/privacy}",
                "followers_url": "https://api.github.com/users/wookayin/followers",
                "following_url": "https://api.github.com/users/wookayin/following{/other_user}",
                "gists_url": "https://api.github.com/users/wookayin/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/wookayin",
                "id": 1009873,
                "login": "wookayin",
                "node_id": "MDQ6VXNlcjEwMDk4NzM=",
                "organizations_url": "https://api.github.com/users/wookayin/orgs",
                "received_events_url": "https://api.github.com/users/wookayin/received_events",
                "repos_url": "https://api.github.com/users/wookayin/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/wookayin/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/wookayin/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/wookayin"
            }
        },
        {
            "author_association": "NONE",
            "body": "> Is there any other config in your shell in your nvim config that sets `$VIMRUNTIME`? That's sounds very strange that `$VIMRUNTIME` points to a wrong directory even if you did a clean-install.\r\n> \r\n> In your shell, please try:\r\n> \r\n> ```shell\r\n> env | grep VIM\r\n> \r\n> bash -c 'echo $VIMRUNTIME'\r\n> \r\n> nvim --clean --headless -c 'echo $VIMRUNTIME' -c 'q'\r\n> ```\r\n\r\nthank you so much for pointing me in the right direction. It was definetily that. I managed to remove all nvim and did a clean install. Turns out it was my previous config.lua that had incorrectly set the path of VIMRUNTIME, but I'm still not sure why. Problem solved.",
            "created_at": "2024-01-11T23:51:56Z",
            "html_url": "https://github.com/neovim/neovim/issues/26906#issuecomment-1888150005",
            "id": 1888150005,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/26906",
            "node_id": "IC_kwDOAPphoM5wiuH1",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1888150005/reactions"
            },
            "updated_at": "2024-01-11T23:51:56Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1888150005",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/87588457?v=4",
                "events_url": "https://api.github.com/users/khezerberg/events{/privacy}",
                "followers_url": "https://api.github.com/users/khezerberg/followers",
                "following_url": "https://api.github.com/users/khezerberg/following{/other_user}",
                "gists_url": "https://api.github.com/users/khezerberg/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/khezerberg",
                "id": 87588457,
                "login": "khezerberg",
                "node_id": "MDQ6VXNlcjg3NTg4NDU3",
                "organizations_url": "https://api.github.com/users/khezerberg/orgs",
                "received_events_url": "https://api.github.com/users/khezerberg/received_events",
                "repos_url": "https://api.github.com/users/khezerberg/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/khezerberg/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/khezerberg/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/khezerberg"
            }
        }
    ],
    "comments": 4,
    "comments_url": "https://api.github.com/repos/neovim/neovim/issues/26906/comments",
    "created_at": "2024-01-05T19:17:59Z",
    "events_url": "https://api.github.com/repos/neovim/neovim/issues/26906/events",
    "html_url": "https://github.com/neovim/neovim/issues/26906",
    "id": 2067913028,
    "labels": [
        {
            "color": "e6e6e6",
            "default": false,
            "description": "Issues that are closed as \"invalid\"",
            "id": 77997477,
            "name": "closed:invalid",
            "node_id": "MDU6TGFiZWw3Nzk5NzQ3Nw==",
            "url": "https://api.github.com/repos/neovim/neovim/labels/closed:invalid"
        }
    ],
    "labels_url": "https://api.github.com/repos/neovim/neovim/issues/26906/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOAPphoM57QdlE",
    "number": 26906,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/neovim/neovim/issues/26906/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/neovim",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/neovim/neovim/issues/26906/timeline",
    "title": "VIMRUNTIME error",
    "updated_at": "2024-01-11T23:55:55Z",
    "url": "https://api.github.com/repos/neovim/neovim/issues/26906",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/87588457?v=4",
        "events_url": "https://api.github.com/users/khezerberg/events{/privacy}",
        "followers_url": "https://api.github.com/users/khezerberg/followers",
        "following_url": "https://api.github.com/users/khezerberg/following{/other_user}",
        "gists_url": "https://api.github.com/users/khezerberg/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/khezerberg",
        "id": 87588457,
        "login": "khezerberg",
        "node_id": "MDQ6VXNlcjg3NTg4NDU3",
        "organizations_url": "https://api.github.com/users/khezerberg/orgs",
        "received_events_url": "https://api.github.com/users/khezerberg/received_events",
        "repos_url": "https://api.github.com/users/khezerberg/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/khezerberg/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/khezerberg/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/khezerberg"
    }
}