{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "### Problem\n\nI've encountered an issue where Neovim exits with a status code of 134, indicating an abort signal, when executing a function that makes a system call during the editor's exit sequence. This behavior occurs even with a minimal Neovim configuration, suggesting it is not related to any plugins or complex setup.\n\n### Steps to reproduce\n\nnvim --clean -c \"autocmd VimLeavePre * call system('echo test')\"\r\n\n\n### Expected behavior\n\nNeovim should exit cleanly without any error codes, even when performing system calls during the exit sequence.\n\n### Neovim version (nvim -v)\n\n0.9.5\n\n### Vim (not Nvim) behaves the same?\n\nNo, vim 9.0.2136\n\n### Operating system/version\n\nmacOS 14.3.1\n\n### Terminal name/version\n\niterm 2 (3.4.23)\n\n### $TERM environment variable\n\nxterm-256color\n\n### Installation\n\nhomebrew",
    "closed_at": "2024-02-13T06:11:38Z",
    "comment_data": [
        {
            "author_association": "MEMBER",
            "body": "Duplicate of #21856",
            "created_at": "2024-02-13T06:11:38Z",
            "html_url": "https://github.com/neovim/neovim/issues/27456#issuecomment-1940485157",
            "id": 1940485157,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/27456",
            "node_id": "IC_kwDOAPphoM5zqXQl",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 1,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1940485157/reactions"
            },
            "updated_at": "2024-02-13T06:11:38Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1940485157",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/35768171?v=4",
                "events_url": "https://api.github.com/users/zeertzjq/events{/privacy}",
                "followers_url": "https://api.github.com/users/zeertzjq/followers",
                "following_url": "https://api.github.com/users/zeertzjq/following{/other_user}",
                "gists_url": "https://api.github.com/users/zeertzjq/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/zeertzjq",
                "id": 35768171,
                "login": "zeertzjq",
                "node_id": "MDQ6VXNlcjM1NzY4MTcx",
                "organizations_url": "https://api.github.com/users/zeertzjq/orgs",
                "received_events_url": "https://api.github.com/users/zeertzjq/received_events",
                "repos_url": "https://api.github.com/users/zeertzjq/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/zeertzjq/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/zeertzjq/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/zeertzjq"
            }
        }
    ],
    "comments": 1,
    "comments_url": "https://api.github.com/repos/neovim/neovim/issues/27456/comments",
    "created_at": "2024-02-13T06:04:26Z",
    "events_url": "https://api.github.com/repos/neovim/neovim/issues/27456/events",
    "html_url": "https://github.com/neovim/neovim/issues/27456",
    "id": 2131526689,
    "labels": [
        {
            "color": "e6e6e6",
            "default": false,
            "description": "issues that are closed as duplicates of other issues",
            "id": 3221613764,
            "name": "closed:duplicate",
            "node_id": "MDU6TGFiZWwzMjIxNjEzNzY0",
            "url": "https://api.github.com/repos/neovim/neovim/labels/closed:duplicate"
        }
    ],
    "labels_url": "https://api.github.com/repos/neovim/neovim/issues/27456/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOAPphoM5_DIQh",
    "number": 27456,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/neovim/neovim/issues/27456/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/neovim",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/neovim/neovim/issues/27456/timeline",
    "title": "Neovim Exits with Code 134 on System Call during Exit Sequence",
    "updated_at": "2024-02-13T06:11:47Z",
    "url": "https://api.github.com/repos/neovim/neovim/issues/27456",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/64197?v=4",
        "events_url": "https://api.github.com/users/rockydd/events{/privacy}",
        "followers_url": "https://api.github.com/users/rockydd/followers",
        "following_url": "https://api.github.com/users/rockydd/following{/other_user}",
        "gists_url": "https://api.github.com/users/rockydd/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/rockydd",
        "id": 64197,
        "login": "rockydd",
        "node_id": "MDQ6VXNlcjY0MTk3",
        "organizations_url": "https://api.github.com/users/rockydd/orgs",
        "received_events_url": "https://api.github.com/users/rockydd/received_events",
        "repos_url": "https://api.github.com/users/rockydd/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/rockydd/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/rockydd/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/rockydd"
    }
}