{
    "active_lock_reason": "resolved",
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "<!-- Before reporting: search existing issues and check the FAQ. -->\r\n\r\n- `nvim --version`: v0.4.0-609\r\n- Vim (version: ) behaves differently? 8.1.1073 - Yes\r\n- Operating system/version: Antergos (Arch Linux)\r\n- Terminal name/version: terminator 1.91-6\r\n- `$TERM`: xterm-256color\r\n\r\n### Steps to reproduce using `nvim -u NORC`\r\n\r\n```\r\nnvim -u NORC\r\n\r\n```\r\n\r\n### Actual behaviour\r\nI've configured Neovim on my main system and it works fine, so I've copied everything from   `~/.local/share/nvim/` and pasted into the same location on a VM I've got and installed Neovim on the VM. Now, when I open Neovim I see no errors but when I close it, I get this error:\r\n\r\n`E886: System error while opening ShaDa file for writing: no such file or directory\r\n`\r\n\r\nThere is this file:\r\n\r\n`~/.local/share/nvim/shada/main.shada`\r\n\r\nalready. I don't understand why Neovim is complaining.\r\nI have deleted and re-installed Neovim in case it gets recreated but that was not the case. I'm still getting the same error.\r\n\r\n### Expected behaviour\r\n\r\nNo errors...",
    "closed_at": "2019-04-16T18:09:34Z",
    "comment_data": [
        {
            "author_association": "NONE",
            "body": "Same here.",
            "created_at": "2019-04-16T14:29:12Z",
            "html_url": "https://github.com/neovim/neovim/issues/9912#issuecomment-483685755",
            "id": 483685755,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/9912",
            "node_id": "MDEyOklzc3VlQ29tbWVudDQ4MzY4NTc1NQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 3,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 3,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/483685755/reactions"
            },
            "updated_at": "2019-04-16T14:29:12Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/483685755",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1180019?v=4",
                "events_url": "https://api.github.com/users/bnjbvr/events{/privacy}",
                "followers_url": "https://api.github.com/users/bnjbvr/followers",
                "following_url": "https://api.github.com/users/bnjbvr/following{/other_user}",
                "gists_url": "https://api.github.com/users/bnjbvr/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/bnjbvr",
                "id": 1180019,
                "login": "bnjbvr",
                "node_id": "MDQ6VXNlcjExODAwMTk=",
                "organizations_url": "https://api.github.com/users/bnjbvr/orgs",
                "received_events_url": "https://api.github.com/users/bnjbvr/received_events",
                "repos_url": "https://api.github.com/users/bnjbvr/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/bnjbvr/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/bnjbvr/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/bnjbvr"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "The problem is known and we discussed it internally. It happens since: https://github.com/neovim/neovim/pull/9907\r\n\r\nFix will follow very soon.",
            "created_at": "2019-04-16T14:30:42Z",
            "html_url": "https://github.com/neovim/neovim/issues/9912#issuecomment-483686382",
            "id": 483686382,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/9912",
            "node_id": "MDEyOklzc3VlQ29tbWVudDQ4MzY4NjM4Mg==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 7,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 7,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/483686382/reactions"
            },
            "updated_at": "2019-04-16T14:30:42Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/483686382",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/972014?v=4",
                "events_url": "https://api.github.com/users/mhinz/events{/privacy}",
                "followers_url": "https://api.github.com/users/mhinz/followers",
                "following_url": "https://api.github.com/users/mhinz/following{/other_user}",
                "gists_url": "https://api.github.com/users/mhinz/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/mhinz",
                "id": 972014,
                "login": "mhinz",
                "node_id": "MDQ6VXNlcjk3MjAxNA==",
                "organizations_url": "https://api.github.com/users/mhinz/orgs",
                "received_events_url": "https://api.github.com/users/mhinz/received_events",
                "repos_url": "https://api.github.com/users/mhinz/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/mhinz/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/mhinz/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/mhinz"
            }
        },
        {
            "author_association": "NONE",
            "body": "I solved this problem temporarily by explicitly defining this in my vimrc:\r\n```vim\r\nlet &viminfofile = expand('$XDG_DATA_HOME/nvim/shada/main.shada')\r\n```\r\nThat has silenced the errors and has seemingly given me access to history again.",
            "created_at": "2019-04-16T16:13:59Z",
            "html_url": "https://github.com/neovim/neovim/issues/9912#issuecomment-483729323",
            "id": 483729323,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/9912",
            "node_id": "MDEyOklzc3VlQ29tbWVudDQ4MzcyOTMyMw==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 4,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 4,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/483729323/reactions"
            },
            "updated_at": "2019-04-16T16:13:59Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/483729323",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/26119366?v=4",
                "events_url": "https://api.github.com/users/comfortablynick/events{/privacy}",
                "followers_url": "https://api.github.com/users/comfortablynick/followers",
                "following_url": "https://api.github.com/users/comfortablynick/following{/other_user}",
                "gists_url": "https://api.github.com/users/comfortablynick/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/comfortablynick",
                "id": 26119366,
                "login": "comfortablynick",
                "node_id": "MDQ6VXNlcjI2MTE5MzY2",
                "organizations_url": "https://api.github.com/users/comfortablynick/orgs",
                "received_events_url": "https://api.github.com/users/comfortablynick/received_events",
                "repos_url": "https://api.github.com/users/comfortablynick/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/comfortablynick/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/comfortablynick/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/comfortablynick"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Should work again.\r\n\r\n@comfortablynick `&shadafile`, please. :)",
            "created_at": "2019-04-16T18:15:18Z",
            "html_url": "https://github.com/neovim/neovim/issues/9912#issuecomment-483786121",
            "id": 483786121,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/9912",
            "node_id": "MDEyOklzc3VlQ29tbWVudDQ4Mzc4NjEyMQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 1,
                "laugh": 0,
                "rocket": 0,
                "total_count": 2,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/483786121/reactions"
            },
            "updated_at": "2019-04-16T18:15:18Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/483786121",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/972014?v=4",
                "events_url": "https://api.github.com/users/mhinz/events{/privacy}",
                "followers_url": "https://api.github.com/users/mhinz/followers",
                "following_url": "https://api.github.com/users/mhinz/following{/other_user}",
                "gists_url": "https://api.github.com/users/mhinz/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/mhinz",
                "id": 972014,
                "login": "mhinz",
                "node_id": "MDQ6VXNlcjk3MjAxNA==",
                "organizations_url": "https://api.github.com/users/mhinz/orgs",
                "received_events_url": "https://api.github.com/users/mhinz/received_events",
                "repos_url": "https://api.github.com/users/mhinz/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/mhinz/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/mhinz/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/mhinz"
            }
        },
        {
            "author_association": "NONE",
            "body": "> NVIM v0.2.2\r\n> Build type: RelWithDebInfo\r\n> LuaJIT 2.1.0-beta3\r\n> Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-_mzR4z/neovim-0.2.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=2 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim-_mzR4z/neovim-0.2.2/build/config -I/build/neovim-_mzR4z/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim-_mzR4z/neovim-0.2.2/build/src/nvim/auto -I/build/neovim-_mzR4z/neovim-0.2.2/build/include\r\n> Compiled by pkg-vim-maintainers@lists.alioth.debian.org\r\n> \r\n> Features: +acl +iconv +jemalloc +tui \r\n> See \":help feature-compile\"\r\n> \r\n>    system vimrc file: \"$VIM/sysinit.vim\"\r\n>   fall-back for $VIM: \"/usr/share/nvim\"\r\n> \r\n> Run :checkhealth for more info\r\n\r\nI still get the error.",
            "created_at": "2019-11-19T14:03:22Z",
            "html_url": "https://github.com/neovim/neovim/issues/9912#issuecomment-555521211",
            "id": 555521211,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/9912",
            "node_id": "MDEyOklzc3VlQ29tbWVudDU1NTUyMTIxMQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/555521211/reactions"
            },
            "updated_at": "2019-11-19T14:03:22Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/555521211",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/47920928?v=4",
                "events_url": "https://api.github.com/users/sajusat/events{/privacy}",
                "followers_url": "https://api.github.com/users/sajusat/followers",
                "following_url": "https://api.github.com/users/sajusat/following{/other_user}",
                "gists_url": "https://api.github.com/users/sajusat/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/sajusat",
                "id": 47920928,
                "login": "sajusat",
                "node_id": "MDQ6VXNlcjQ3OTIwOTI4",
                "organizations_url": "https://api.github.com/users/sajusat/orgs",
                "received_events_url": "https://api.github.com/users/sajusat/received_events",
                "repos_url": "https://api.github.com/users/sajusat/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/sajusat/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/sajusat/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/sajusat"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "@sajusat You're using Nvim v0.2.2, but the latest release is v0.4.3. You're missing over 4000 patches.",
            "created_at": "2019-11-19T14:13:00Z",
            "html_url": "https://github.com/neovim/neovim/issues/9912#issuecomment-555525048",
            "id": 555525048,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/9912",
            "node_id": "MDEyOklzc3VlQ29tbWVudDU1NTUyNTA0OA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/555525048/reactions"
            },
            "updated_at": "2019-11-19T14:13:00Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/555525048",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/972014?v=4",
                "events_url": "https://api.github.com/users/mhinz/events{/privacy}",
                "followers_url": "https://api.github.com/users/mhinz/followers",
                "following_url": "https://api.github.com/users/mhinz/following{/other_user}",
                "gists_url": "https://api.github.com/users/mhinz/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/mhinz",
                "id": 972014,
                "login": "mhinz",
                "node_id": "MDQ6VXNlcjk3MjAxNA==",
                "organizations_url": "https://api.github.com/users/mhinz/orgs",
                "received_events_url": "https://api.github.com/users/mhinz/received_events",
                "repos_url": "https://api.github.com/users/mhinz/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/mhinz/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/mhinz/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/mhinz"
            }
        },
        {
            "author_association": "NONE",
            "body": "> @sajusat You're using Nvim v0.2.2, but the latest release is v0.4.3. You're missing over 4000 patches.\r\n\r\n@mhinz Sorry about the confusion. I just installed neovim using *sudo apt-get install neovim* with Ubuntu 18.04.3 LTS. I was expecting that they were updating it regularly. I didn't see the difference in versions. ",
            "created_at": "2019-11-24T09:41:12Z",
            "html_url": "https://github.com/neovim/neovim/issues/9912#issuecomment-557872607",
            "id": 557872607,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/9912",
            "node_id": "MDEyOklzc3VlQ29tbWVudDU1Nzg3MjYwNw==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 2,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 2,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/557872607/reactions"
            },
            "updated_at": "2019-11-24T09:41:55Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/557872607",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/47920928?v=4",
                "events_url": "https://api.github.com/users/sajusat/events{/privacy}",
                "followers_url": "https://api.github.com/users/sajusat/followers",
                "following_url": "https://api.github.com/users/sajusat/following{/other_user}",
                "gists_url": "https://api.github.com/users/sajusat/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/sajusat",
                "id": 47920928,
                "login": "sajusat",
                "node_id": "MDQ6VXNlcjQ3OTIwOTI4",
                "organizations_url": "https://api.github.com/users/sajusat/orgs",
                "received_events_url": "https://api.github.com/users/sajusat/received_events",
                "repos_url": "https://api.github.com/users/sajusat/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/sajusat/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/sajusat/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/sajusat"
            }
        },
        {
            "author_association": "NONE",
            "body": "I got this error on elementaryOS 5.1, Neovim v0.2.2. For some reason the following files came with their ownership set to the `root` user: \r\n``` bash\r\n/home/<user>/.local/share/nvim\r\n/home/<user>/.local/share/nvim/swap\r\n/home/<user>/.local/share/nvim/shada\r\n/home/<user>/.local/share/nvim/shada/main.shada\r\n```\r\n\r\nRunning \r\n``` bash\r\nsudo  find . -not -user <user> -exec chown -R <user>:<group> {} \\;\r\n```\r\nsolved the problem.",
            "created_at": "2019-12-17T00:50:18Z",
            "html_url": "https://github.com/neovim/neovim/issues/9912#issuecomment-566320203",
            "id": 566320203,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/9912",
            "node_id": "MDEyOklzc3VlQ29tbWVudDU2NjMyMDIwMw==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 22,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 3,
                "laugh": 0,
                "rocket": 0,
                "total_count": 25,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/566320203/reactions"
            },
            "updated_at": "2019-12-17T00:50:18Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/566320203",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/8756851?v=4",
                "events_url": "https://api.github.com/users/hiagop/events{/privacy}",
                "followers_url": "https://api.github.com/users/hiagop/followers",
                "following_url": "https://api.github.com/users/hiagop/following{/other_user}",
                "gists_url": "https://api.github.com/users/hiagop/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/hiagop",
                "id": 8756851,
                "login": "hiagop",
                "node_id": "MDQ6VXNlcjg3NTY4NTE=",
                "organizations_url": "https://api.github.com/users/hiagop/orgs",
                "received_events_url": "https://api.github.com/users/hiagop/received_events",
                "repos_url": "https://api.github.com/users/hiagop/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/hiagop/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/hiagop/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/hiagop"
            }
        },
        {
            "author_association": "NONE",
            "body": "OS - macOS Mojave. \r\nInstalled dev version of neovim `brew install --HEAD neovim`. Double-checked that version isn't outdated:\r\n```\r\nnvim -version \r\nNVIM v0.5.0-nightly\r\nBuild type: Release\r\nLuaJIT 2.0.5\r\n```\r\nTried running as normal user `nvim test` - got an error:\r\n```\r\nError detected while processing function <SNR>14_LoadRemotePlugins[1]..<SNR>14_G\r\netManifest[1]..<SNR>14_GetManifestPath:\r\nline   10:\r\nE739: Cannot create directory /Users/USERNAME/.local/share: permission denied\r\nE886: System error while opening ShaDa file /Users/USERNAME/.local/share/nvim/sha\r\nda/main.shada for reading: permission denied\r\nE303: Unable to create directory \"/Users/USERNAME/.local/share\" for swap file, re\r\ncovery impossible: permission denied\r\nE303: Unable to open swap file for \"test\", recovery impossible\r\nE886: System error while opening ShaDa file /Users/USERNAME/.local/share/nvim/sha\r\nda/main.shada for reading: permission denied\r\nPress ENTER or type command to continue\r\n```\r\n\r\nRan as root later on - didn't any errors. But running as regular user still gives me error. Removed `.local/share/nvim` directory in hopes it would recreate when I ran as normal user again - nope, still an error. ",
            "created_at": "2020-03-14T23:08:58Z",
            "html_url": "https://github.com/neovim/neovim/issues/9912#issuecomment-599146031",
            "id": 599146031,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/9912",
            "node_id": "MDEyOklzc3VlQ29tbWVudDU5OTE0NjAzMQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/599146031/reactions"
            },
            "updated_at": "2022-01-27T01:39:25Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/599146031",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/40537713?v=4",
                "events_url": "https://api.github.com/users/wary-hermit/events{/privacy}",
                "followers_url": "https://api.github.com/users/wary-hermit/followers",
                "following_url": "https://api.github.com/users/wary-hermit/following{/other_user}",
                "gists_url": "https://api.github.com/users/wary-hermit/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/wary-hermit",
                "id": 40537713,
                "login": "wary-hermit",
                "node_id": "MDQ6VXNlcjQwNTM3NzEz",
                "organizations_url": "https://api.github.com/users/wary-hermit/orgs",
                "received_events_url": "https://api.github.com/users/wary-hermit/received_events",
                "repos_url": "https://api.github.com/users/wary-hermit/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/wary-hermit/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/wary-hermit/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/wary-hermit"
            }
        },
        {
            "author_association": "NONE",
            "body": "Confirm, I get this issue on a regular brew install. chowning the relevant ~/.local/share/nvim files and directories fixed it\r\n\r\n```\r\n❯ nvim --version\r\nNVIM v0.4.4\r\nBuild type: Release\r\nLuaJIT 2.0.5\r\nCompilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/build/config -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/src -I/usr/local/include -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/build/src/nvim/auto -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/build/include\r\nCompiled by brew@Catalina\r\n\r\nFeatures: +acl +iconv +tui\r\nSee \":help feature-compile\"\r\n\r\n   system vimrc file: \"$VIM/sysinit.vim\"\r\n  fall-back for $VIM: \"/usr/local/Cellar/neovim/0.4.4/share/nvim\"\r\n\r\nRun :checkhealth for more info\r\n```\r\n\r\n```\r\nvim ~/test\r\nE886: System error while opening ShaDa file /Users/nathanwest/.local/share/nvim/shada/main.shada for reading: permission denied\r\nE303: Unable to create directory \"/Users/nathanwest/.local/share/nvim/swap\" for swap file, recovery impossible: permission denied\r\nE303: Unable to open swap file for \"/Users/nathanwest/test\", recovery impossible\r\nE886: System error while opening ShaDa file /Users/nathanwest/.local/share/nvim/shada/main.shada for reading: permission denied\r\nPress ENTER or type command to continue\r\n```",
            "created_at": "2020-09-03T19:09:37Z",
            "html_url": "https://github.com/neovim/neovim/issues/9912#issuecomment-686701730",
            "id": 686701730,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/9912",
            "node_id": "MDEyOklzc3VlQ29tbWVudDY4NjcwMTczMA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/686701730/reactions"
            },
            "updated_at": "2020-09-03T19:13:13Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/686701730",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1823405?v=4",
                "events_url": "https://api.github.com/users/Lucretiel/events{/privacy}",
                "followers_url": "https://api.github.com/users/Lucretiel/followers",
                "following_url": "https://api.github.com/users/Lucretiel/following{/other_user}",
                "gists_url": "https://api.github.com/users/Lucretiel/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/Lucretiel",
                "id": 1823405,
                "login": "Lucretiel",
                "node_id": "MDQ6VXNlcjE4MjM0MDU=",
                "organizations_url": "https://api.github.com/users/Lucretiel/orgs",
                "received_events_url": "https://api.github.com/users/Lucretiel/received_events",
                "repos_url": "https://api.github.com/users/Lucretiel/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/Lucretiel/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Lucretiel/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/Lucretiel"
            }
        },
        {
            "author_association": "NONE",
            "body": "same here, \r\n```\r\n❯ nvim --version\r\nNVIM v0.4.4\r\nBuild type: Release\r\nLuaJIT 2.1.0-beta3\r\nCompilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20210318-48132-k7r45c/neovim-0.4.4/build/config -I/tmp/neovim-20210318-48132-k7r45c/neovim-0.4.4/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210318-48132-k7r45c/neovim-0.4.4/build/src/nvim/auto -I/tmp/neovim-20210318-48132-k7r45c/neovim-0.4.4/build/include\r\nCompiled by brew@BigSur\r\n```",
            "created_at": "2021-03-22T10:15:54Z",
            "html_url": "https://github.com/neovim/neovim/issues/9912#issuecomment-803945836",
            "id": 803945836,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/9912",
            "node_id": "MDEyOklzc3VlQ29tbWVudDgwMzk0NTgzNg==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/803945836/reactions"
            },
            "updated_at": "2021-03-22T10:15:54Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/803945836",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/429211?v=4",
                "events_url": "https://api.github.com/users/tlightsky/events{/privacy}",
                "followers_url": "https://api.github.com/users/tlightsky/followers",
                "following_url": "https://api.github.com/users/tlightsky/following{/other_user}",
                "gists_url": "https://api.github.com/users/tlightsky/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/tlightsky",
                "id": 429211,
                "login": "tlightsky",
                "node_id": "MDQ6VXNlcjQyOTIxMQ==",
                "organizations_url": "https://api.github.com/users/tlightsky/orgs",
                "received_events_url": "https://api.github.com/users/tlightsky/received_events",
                "repos_url": "https://api.github.com/users/tlightsky/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/tlightsky/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/tlightsky/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/tlightsky"
            }
        },
        {
            "author_association": "NONE",
            "body": "Hello, I am having the same issue and I could not find a way to fix it. @Lucretiel could you specify the exact `chown` command you performed? @tlightsky I get the same output when I run `nvim --version`. Were you able to solve it?",
            "created_at": "2021-04-04T09:03:03Z",
            "html_url": "https://github.com/neovim/neovim/issues/9912#issuecomment-812999391",
            "id": 812999391,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/9912",
            "node_id": "MDEyOklzc3VlQ29tbWVudDgxMjk5OTM5MQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/812999391/reactions"
            },
            "updated_at": "2021-04-04T09:03:03Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/812999391",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/42862428?v=4",
                "events_url": "https://api.github.com/users/xplosionmind/events{/privacy}",
                "followers_url": "https://api.github.com/users/xplosionmind/followers",
                "following_url": "https://api.github.com/users/xplosionmind/following{/other_user}",
                "gists_url": "https://api.github.com/users/xplosionmind/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/xplosionmind",
                "id": 42862428,
                "login": "xplosionmind",
                "node_id": "MDQ6VXNlcjQyODYyNDI4",
                "organizations_url": "https://api.github.com/users/xplosionmind/orgs",
                "received_events_url": "https://api.github.com/users/xplosionmind/received_events",
                "repos_url": "https://api.github.com/users/xplosionmind/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/xplosionmind/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/xplosionmind/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/xplosionmind"
            }
        },
        {
            "author_association": "NONE",
            "body": "> Hello, I am having the same issue and I could not find a way to fix it. @Lucretiel could you specify the exact `chown` command you performed? @tlightsky I get the same output when I run `nvim --version`. Were you able to solve it?\r\n\r\nThis fixed it for me on macOS: \r\n\r\n```\r\nsudo chown {username} ~/.local\r\nsudo chown {username} ~/.local/share\r\nsudo chown {username} ~/.local/share/nvim\r\nsudo chown {username} ~/.local/share/nvim/shada\r\nsudo chown {username} ~/.local/share/nvim/shada/main.shada\r\nsudo chown {username} ~/.local/share/nvim/swap\r\n```",
            "created_at": "2021-05-20T08:48:04Z",
            "html_url": "https://github.com/neovim/neovim/issues/9912#issuecomment-844873913",
            "id": 844873913,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/9912",
            "node_id": "MDEyOklzc3VlQ29tbWVudDg0NDg3MzkxMw==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 9,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 9,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/844873913/reactions"
            },
            "updated_at": "2021-05-20T08:48:36Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/844873913",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/40537713?v=4",
                "events_url": "https://api.github.com/users/wary-hermit/events{/privacy}",
                "followers_url": "https://api.github.com/users/wary-hermit/followers",
                "following_url": "https://api.github.com/users/wary-hermit/following{/other_user}",
                "gists_url": "https://api.github.com/users/wary-hermit/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/wary-hermit",
                "id": 40537713,
                "login": "wary-hermit",
                "node_id": "MDQ6VXNlcjQwNTM3NzEz",
                "organizations_url": "https://api.github.com/users/wary-hermit/orgs",
                "received_events_url": "https://api.github.com/users/wary-hermit/received_events",
                "repos_url": "https://api.github.com/users/wary-hermit/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/wary-hermit/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/wary-hermit/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/wary-hermit"
            }
        },
        {
            "author_association": "NONE",
            "body": "> > Hello, I am having the same issue and I could not find a way to fix it. @Lucretiel could you specify the exact `chown` command you performed? @tlightsky I get the same output when I run `nvim --version`. Were you able to solve it?\r\n> \r\n> This fixed it for me on macOS:\r\n> \r\n> ```\r\n> sudo chown {username} ~/.local\r\n> sudo chown {username} ~/.local/share\r\n> sudo chown {username} ~/.local/share/nvim\r\n> sudo chown {username} ~/.local/share/nvim/shada\r\n> sudo chown {username} ~/.local/share/nvim/shada/main.shada\r\n> sudo chown {username} ~/.local/share/nvim/swap\r\n> ```\r\n\r\nThese commands can be reduced to `sudo chown -R \"${USER}\" ~/.local` if you don't mind `chown`ing the entire directory for your user, which likely is the case given that it's in your user directory",
            "created_at": "2022-02-05T15:18:33Z",
            "html_url": "https://github.com/neovim/neovim/issues/9912#issuecomment-1030643286",
            "id": 1030643286,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/9912",
            "node_id": "IC_kwDOAPphoM49bl5W",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 20,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 1,
                "laugh": 0,
                "rocket": 0,
                "total_count": 21,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1030643286/reactions"
            },
            "updated_at": "2022-02-05T15:18:33Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1030643286",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/13588509?v=4",
                "events_url": "https://api.github.com/users/nick-bull/events{/privacy}",
                "followers_url": "https://api.github.com/users/nick-bull/followers",
                "following_url": "https://api.github.com/users/nick-bull/following{/other_user}",
                "gists_url": "https://api.github.com/users/nick-bull/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/nick-bull",
                "id": 13588509,
                "login": "nick-bull",
                "node_id": "MDQ6VXNlcjEzNTg4NTA5",
                "organizations_url": "https://api.github.com/users/nick-bull/orgs",
                "received_events_url": "https://api.github.com/users/nick-bull/received_events",
                "repos_url": "https://api.github.com/users/nick-bull/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/nick-bull/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/nick-bull/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/nick-bull"
            }
        },
        {
            "author_association": "NONE",
            "body": "chown didnt help for me",
            "created_at": "2022-08-14T20:05:19Z",
            "html_url": "https://github.com/neovim/neovim/issues/9912#issuecomment-1214440431",
            "id": 1214440431,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/9912",
            "node_id": "IC_kwDOAPphoM5IYuPv",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1214440431/reactions"
            },
            "updated_at": "2022-08-14T20:05:19Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1214440431",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/39703898?v=4",
                "events_url": "https://api.github.com/users/bluebrown/events{/privacy}",
                "followers_url": "https://api.github.com/users/bluebrown/followers",
                "following_url": "https://api.github.com/users/bluebrown/following{/other_user}",
                "gists_url": "https://api.github.com/users/bluebrown/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/bluebrown",
                "id": 39703898,
                "login": "bluebrown",
                "node_id": "MDQ6VXNlcjM5NzAzODk4",
                "organizations_url": "https://api.github.com/users/bluebrown/orgs",
                "received_events_url": "https://api.github.com/users/bluebrown/received_events",
                "repos_url": "https://api.github.com/users/bluebrown/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/bluebrown/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/bluebrown/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/bluebrown"
            }
        },
        {
            "author_association": "NONE",
            "body": "I still get the error on quitting about the shada file not being writeable due to permissions issues.",
            "created_at": "2022-12-13T10:33:53Z",
            "html_url": "https://github.com/neovim/neovim/issues/9912#issuecomment-1348154199",
            "id": 1348154199,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/9912",
            "node_id": "IC_kwDOAPphoM5QWzNX",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1348154199/reactions"
            },
            "updated_at": "2022-12-13T10:33:53Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1348154199",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/8407819?v=4",
                "events_url": "https://api.github.com/users/vedantroy/events{/privacy}",
                "followers_url": "https://api.github.com/users/vedantroy/followers",
                "following_url": "https://api.github.com/users/vedantroy/following{/other_user}",
                "gists_url": "https://api.github.com/users/vedantroy/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/vedantroy",
                "id": 8407819,
                "login": "vedantroy",
                "node_id": "MDQ6VXNlcjg0MDc4MTk=",
                "organizations_url": "https://api.github.com/users/vedantroy/orgs",
                "received_events_url": "https://api.github.com/users/vedantroy/received_events",
                "repos_url": "https://api.github.com/users/vedantroy/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/vedantroy/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/vedantroy/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/vedantroy"
            }
        },
        {
            "author_association": "NONE",
            "body": "I have the same issue with NVIM v0.8.1. Files in ~/.local/share/nvim and subdirs belong to my user and group, and permissions are 0600.",
            "created_at": "2023-01-14T05:34:42Z",
            "html_url": "https://github.com/neovim/neovim/issues/9912#issuecomment-1382666898",
            "id": 1382666898,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/9912",
            "node_id": "IC_kwDOAPphoM5SadKS",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1382666898/reactions"
            },
            "updated_at": "2023-01-14T05:34:42Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1382666898",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1484549?v=4",
                "events_url": "https://api.github.com/users/ivanovsaleksejs/events{/privacy}",
                "followers_url": "https://api.github.com/users/ivanovsaleksejs/followers",
                "following_url": "https://api.github.com/users/ivanovsaleksejs/following{/other_user}",
                "gists_url": "https://api.github.com/users/ivanovsaleksejs/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/ivanovsaleksejs",
                "id": 1484549,
                "login": "ivanovsaleksejs",
                "node_id": "MDQ6VXNlcjE0ODQ1NDk=",
                "organizations_url": "https://api.github.com/users/ivanovsaleksejs/orgs",
                "received_events_url": "https://api.github.com/users/ivanovsaleksejs/received_events",
                "repos_url": "https://api.github.com/users/ivanovsaleksejs/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/ivanovsaleksejs/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/ivanovsaleksejs/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/ivanovsaleksejs"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "It's now `~/.local/state/nvim`",
            "created_at": "2023-01-14T05:41:03Z",
            "html_url": "https://github.com/neovim/neovim/issues/9912#issuecomment-1382667836",
            "id": 1382667836,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/9912",
            "node_id": "IC_kwDOAPphoM5SadY8",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 4,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 4,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1382667836/reactions"
            },
            "updated_at": "2023-01-14T05:41:03Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1382667836",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/35768171?v=4",
                "events_url": "https://api.github.com/users/zeertzjq/events{/privacy}",
                "followers_url": "https://api.github.com/users/zeertzjq/followers",
                "following_url": "https://api.github.com/users/zeertzjq/following{/other_user}",
                "gists_url": "https://api.github.com/users/zeertzjq/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/zeertzjq",
                "id": 35768171,
                "login": "zeertzjq",
                "node_id": "MDQ6VXNlcjM1NzY4MTcx",
                "organizations_url": "https://api.github.com/users/zeertzjq/orgs",
                "received_events_url": "https://api.github.com/users/zeertzjq/received_events",
                "repos_url": "https://api.github.com/users/zeertzjq/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/zeertzjq/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/zeertzjq/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/zeertzjq"
            }
        },
        {
            "author_association": "NONE",
            "body": "`sudo chown -R \"${USER}\" ~/.local` worked here for fixing E303.\r\n\r\n```\r\nNVIM v0.9.1\r\nBuild type: Release\r\nLuaJIT 2.1.0-beta3\r\n\r\n   system vimrc file: \"$VIM/sysinit.vim\"\r\n  fall-back for $VIM: \"/usr/local/Cellar/neovim/0.9.1/share/nvim\"\r\n\r\nRun :checkhealth for more info\r\n```\r\n\r\nRunning on macOS Ventura.",
            "created_at": "2023-07-28T12:12:24Z",
            "html_url": "https://github.com/neovim/neovim/issues/9912#issuecomment-1655578174",
            "id": 1655578174,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/9912",
            "node_id": "IC_kwDOAPphoM5irh4-",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 2,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 2,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1655578174/reactions"
            },
            "updated_at": "2023-07-28T12:12:24Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1655578174",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/2343891?v=4",
                "events_url": "https://api.github.com/users/dverzolla/events{/privacy}",
                "followers_url": "https://api.github.com/users/dverzolla/followers",
                "following_url": "https://api.github.com/users/dverzolla/following{/other_user}",
                "gists_url": "https://api.github.com/users/dverzolla/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/dverzolla",
                "id": 2343891,
                "login": "dverzolla",
                "node_id": "MDQ6VXNlcjIzNDM4OTE=",
                "organizations_url": "https://api.github.com/users/dverzolla/orgs",
                "received_events_url": "https://api.github.com/users/dverzolla/received_events",
                "repos_url": "https://api.github.com/users/dverzolla/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/dverzolla/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/dverzolla/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/dverzolla"
            }
        },
        {
            "author_association": "NONE",
            "body": "I got the same error.\r\nIt was because permissions of ~/.local/state/nvim/shada/shada.main were not right.\r\nCheck the permission of shada and shada.main file.\r\nexecute this to add read and write permission for file `chmod +r ~/.local/state/nvim/shada/*`",
            "created_at": "2023-10-13T13:00:22Z",
            "html_url": "https://github.com/neovim/neovim/issues/9912#issuecomment-1761482477",
            "id": 1761482477,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/9912",
            "node_id": "IC_kwDOAPphoM5o_hbt",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1761482477/reactions"
            },
            "updated_at": "2023-10-13T13:00:22Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1761482477",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/114930840?v=4",
                "events_url": "https://api.github.com/users/ShailMahan012/events{/privacy}",
                "followers_url": "https://api.github.com/users/ShailMahan012/followers",
                "following_url": "https://api.github.com/users/ShailMahan012/following{/other_user}",
                "gists_url": "https://api.github.com/users/ShailMahan012/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/ShailMahan012",
                "id": 114930840,
                "login": "ShailMahan012",
                "node_id": "U_kgDOBtm0mA",
                "organizations_url": "https://api.github.com/users/ShailMahan012/orgs",
                "received_events_url": "https://api.github.com/users/ShailMahan012/received_events",
                "repos_url": "https://api.github.com/users/ShailMahan012/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/ShailMahan012/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/ShailMahan012/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/ShailMahan012"
            }
        },
        {
            "author_association": "NONE",
            "body": "> `sudo chown -R \"${USER}\" ~/.local` worked here for fixing E303.\r\n> \r\n> ```\r\n> NVIM v0.9.1\r\n> Build type: Release\r\n> LuaJIT 2.1.0-beta3\r\n> \r\n>    system vimrc file: \"$VIM/sysinit.vim\"\r\n>   fall-back for $VIM: \"/usr/local/Cellar/neovim/0.9.1/share/nvim\"\r\n> \r\n> Run :checkhealth for more info\r\n> ```\r\n> \r\n> Running on macOS Ventura.\r\n\r\n\r\nworks bro thanks",
            "created_at": "2024-02-08T08:57:02Z",
            "html_url": "https://github.com/neovim/neovim/issues/9912#issuecomment-1933621538",
            "id": 1933621538,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/9912",
            "node_id": "IC_kwDOAPphoM5zQLki",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1933621538/reactions"
            },
            "updated_at": "2024-02-08T08:57:02Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1933621538",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/98458241?v=4",
                "events_url": "https://api.github.com/users/mohwildan/events{/privacy}",
                "followers_url": "https://api.github.com/users/mohwildan/followers",
                "following_url": "https://api.github.com/users/mohwildan/following{/other_user}",
                "gists_url": "https://api.github.com/users/mohwildan/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/mohwildan",
                "id": 98458241,
                "login": "mohwildan",
                "node_id": "U_kgDOBd5agQ",
                "organizations_url": "https://api.github.com/users/mohwildan/orgs",
                "received_events_url": "https://api.github.com/users/mohwildan/received_events",
                "repos_url": "https://api.github.com/users/mohwildan/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/mohwildan/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/mohwildan/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/mohwildan"
            }
        }
    ],
    "comments": 21,
    "comments_url": "https://api.github.com/repos/neovim/neovim/issues/9912/comments",
    "created_at": "2019-04-16T14:27:30Z",
    "events_url": "https://api.github.com/repos/neovim/neovim/issues/9912/events",
    "html_url": "https://github.com/neovim/neovim/issues/9912",
    "id": 433811617,
    "labels": [
        {
            "color": "f9d0c4",
            "default": false,
            "description": "wrong behavior that was introduced in a previous commit (please bisect)",
            "id": 619474658,
            "name": "bug-regression",
            "node_id": "MDU6TGFiZWw2MTk0NzQ2NTg=",
            "url": "https://api.github.com/repos/neovim/neovim/labels/bug-regression"
        }
    ],
    "labels_url": "https://api.github.com/repos/neovim/neovim/issues/9912/labels{/name}",
    "locked": true,
    "milestone": {
        "closed_at": "2019-09-18T04:28:47Z",
        "closed_issues": 219,
        "created_at": "2018-12-30T22:10:04Z",
        "creator": {
            "avatar_url": "https://avatars.githubusercontent.com/u/1359421?v=4",
            "events_url": "https://api.github.com/users/justinmk/events{/privacy}",
            "followers_url": "https://api.github.com/users/justinmk/followers",
            "following_url": "https://api.github.com/users/justinmk/following{/other_user}",
            "gists_url": "https://api.github.com/users/justinmk/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/justinmk",
            "id": 1359421,
            "login": "justinmk",
            "node_id": "MDQ6VXNlcjEzNTk0MjE=",
            "organizations_url": "https://api.github.com/users/justinmk/orgs",
            "received_events_url": "https://api.github.com/users/justinmk/received_events",
            "repos_url": "https://api.github.com/users/justinmk/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/justinmk/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/justinmk/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/justinmk"
        },
        "description": "",
        "due_on": "2019-09-15T07:00:00Z",
        "html_url": "https://github.com/neovim/neovim/milestone/21",
        "id": 3930226,
        "labels_url": "https://api.github.com/repos/neovim/neovim/milestones/21/labels",
        "node_id": "MDk6TWlsZXN0b25lMzkzMDIyNg==",
        "number": 21,
        "open_issues": 0,
        "state": "closed",
        "title": "0.4",
        "updated_at": "2022-05-04T11:57:42Z",
        "url": "https://api.github.com/repos/neovim/neovim/milestones/21"
    },
    "node_id": "MDU6SXNzdWU0MzM4MTE2MTc=",
    "number": 9912,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 8,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 8,
        "url": "https://api.github.com/repos/neovim/neovim/issues/9912/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/neovim",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/neovim/neovim/issues/9912/timeline",
    "title": "E886: System error while opening ShaDa file for writing: no such file or directory",
    "updated_at": "2024-02-08T09:13:25Z",
    "url": "https://api.github.com/repos/neovim/neovim/issues/9912",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/6114541?v=4",
        "events_url": "https://api.github.com/users/hubitor/events{/privacy}",
        "followers_url": "https://api.github.com/users/hubitor/followers",
        "following_url": "https://api.github.com/users/hubitor/following{/other_user}",
        "gists_url": "https://api.github.com/users/hubitor/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/hubitor",
        "id": 6114541,
        "login": "hubitor",
        "node_id": "MDQ6VXNlcjYxMTQ1NDE=",
        "organizations_url": "https://api.github.com/users/hubitor/orgs",
        "received_events_url": "https://api.github.com/users/hubitor/received_events",
        "repos_url": "https://api.github.com/users/hubitor/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/hubitor/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/hubitor/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/hubitor"
    }
}