{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "I'm trying to run the example code on the main page of the README, namely:\r\n\r\n```python\r\n>>> from pynvim import attach\r\n>>> nvim = attach('child', argv=[\"/bin/env\", \"nvim\", \"--embed\", \"--headless\"])\r\n```\r\n\r\nBut I get an error instead:\r\n\r\n```python\r\n>>> from pynvim import attach\r\n>>> nvim = attach('child', argv=['C:\\\\Users\\\\Toqoz\\\\Documents\\\\code\\\\neovim-test\\\\Neovim2\\\\bin\\\\nvim.exe', '--embed', '--headless'])\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\n  File \"C:\\Users\\Toqoz\\AppData\\Roaming\\Python\\Python39\\site-packages\\pynvim\\__init__.py\", line 122, in attach\r\n    return Nvim.from_session(session).with_decode(decode)\r\n  File \"C:\\Users\\Toqoz\\AppData\\Roaming\\Python\\Python39\\site-packages\\pynvim\\api\\nvim.py\", line 80, in from_session\r\n    channel_id, metadata = session.request(b'nvim_get_api_info')\r\n  File \"C:\\Users\\Toqoz\\AppData\\Roaming\\Python\\Python39\\site-packages\\pynvim\\msgpack_rpc\\session.py\", line 98, in request\r\n    raise OSError('EOF')\r\nOSError: EOF\r\n```\r\n\r\nRunning the same thing from a script gives a bit more info, but I think it's irrelevant:\r\n```\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\Toqoz\\Documents\\code\\neovim-test\\something.py\", line 4, in <module>\r\n    nvim = attach('child', argv=['C:\\\\Users\\\\Toqoz\\\\Documents\\\\code\\\\neovim-test\\\\Neovim2\\\\bin\\\\nvim.exe', \"--embed\"])\r\n  File \"C:\\Users\\Toqoz\\AppData\\Roaming\\Python\\Python39\\site-packages\\pynvim\\__init__.py\", line 122, in attach\r\n    return Nvim.from_session(session).with_decode(decode)\r\n  File \"C:\\Users\\Toqoz\\AppData\\Roaming\\Python\\Python39\\site-packages\\pynvim\\api\\nvim.py\", line 80, in from_session\r\n    channel_id, metadata = session.request(b'nvim_get_api_info')\r\n  File \"C:\\Users\\Toqoz\\AppData\\Roaming\\Python\\Python39\\site-packages\\pynvim\\msgpack_rpc\\session.py\", line 98, in request\r\n    raise OSError('EOF')\r\nOSError: EOF\r\nException ignored in: <function BaseSubprocessTransport.__del__ at 0x00000254C7607D30>\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\Toqoz\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\base_subprocess.py\", line 126, in __del__\r\n  File \"C:\\Users\\Toqoz\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\base_subprocess.py\", line 104, in close\r\n  File \"C:\\Users\\Toqoz\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\proactor_events.py\", line 108, in close\r\n  File \"C:\\Users\\Toqoz\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\base_events.py\", line 746, in call_soon\r\n  File \"C:\\Users\\Toqoz\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\base_events.py\", line 510, in _check_closed\r\nRuntimeError: Event loop is closed\r\nException ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000254C7637670>\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\Toqoz\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\proactor_events.py\", line 115, in __del__\r\n  File \"C:\\Users\\Toqoz\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\proactor_events.py\", line 79, in __repr__\r\n  File \"C:\\Users\\Toqoz\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\windows_utils.py\", line 102, in fileno\r\nValueError: I/O operation on closed pipe\r\n```\r\n\r\nAny pointers?  I've also tried connecting using a socket but that also behaves weirdly on Windows.\r\n\r\n```\r\n$ python -- version\r\nPython 3.9.6\r\n```",
    "closed_at": null,
    "comment_data": [
        {
            "author_association": "CONTRIBUTOR",
            "body": "The neovim is already running?  I think it is not running.",
            "created_at": "2022-04-11T23:48:47Z",
            "html_url": "https://github.com/neovim/pynvim/issues/505#issuecomment-1095703417",
            "id": 1095703417,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/505",
            "node_id": "IC_kwDOASpKTs5BTxt5",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1095703417/reactions"
            },
            "updated_at": "2022-04-11T23:48:47Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1095703417",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/41495?v=4",
                "events_url": "https://api.github.com/users/Shougo/events{/privacy}",
                "followers_url": "https://api.github.com/users/Shougo/followers",
                "following_url": "https://api.github.com/users/Shougo/following{/other_user}",
                "gists_url": "https://api.github.com/users/Shougo/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/Shougo",
                "id": 41495,
                "login": "Shougo",
                "node_id": "MDQ6VXNlcjQxNDk1",
                "organizations_url": "https://api.github.com/users/Shougo/orgs",
                "received_events_url": "https://api.github.com/users/Shougo/received_events",
                "repos_url": "https://api.github.com/users/Shougo/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/Shougo/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Shougo/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/Shougo"
            }
        },
        {
            "author_association": "NONE",
            "body": "I thought the purpose of this code was to launch neovim as a child process and attach to that.\r\n\r\nIf I launch neovim (externally, just by running it) and then run the code I get the same error.",
            "created_at": "2022-04-12T08:17:31Z",
            "html_url": "https://github.com/neovim/pynvim/issues/505#issuecomment-1096332299",
            "id": 1096332299,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/505",
            "node_id": "IC_kwDOASpKTs5BWLQL",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1096332299/reactions"
            },
            "updated_at": "2022-04-12T08:17:31Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1096332299",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/6947819?v=4",
                "events_url": "https://api.github.com/users/Toqozz/events{/privacy}",
                "followers_url": "https://api.github.com/users/Toqozz/followers",
                "following_url": "https://api.github.com/users/Toqozz/following{/other_user}",
                "gists_url": "https://api.github.com/users/Toqozz/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/Toqozz",
                "id": 6947819,
                "login": "Toqozz",
                "node_id": "MDQ6VXNlcjY5NDc4MTk=",
                "organizations_url": "https://api.github.com/users/Toqozz/orgs",
                "received_events_url": "https://api.github.com/users/Toqozz/received_events",
                "repos_url": "https://api.github.com/users/Toqozz/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/Toqozz/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Toqozz/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/Toqozz"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "The backslash escape is needed in single quotes?",
            "created_at": "2022-04-12T08:45:45Z",
            "html_url": "https://github.com/neovim/pynvim/issues/505#issuecomment-1096379426",
            "id": 1096379426,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/505",
            "node_id": "IC_kwDOASpKTs5BWWwi",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1096379426/reactions"
            },
            "updated_at": "2022-04-12T08:45:45Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1096379426",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/41495?v=4",
                "events_url": "https://api.github.com/users/Shougo/events{/privacy}",
                "followers_url": "https://api.github.com/users/Shougo/followers",
                "following_url": "https://api.github.com/users/Shougo/following{/other_user}",
                "gists_url": "https://api.github.com/users/Shougo/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/Shougo",
                "id": 41495,
                "login": "Shougo",
                "node_id": "MDQ6VXNlcjQxNDk1",
                "organizations_url": "https://api.github.com/users/Shougo/orgs",
                "received_events_url": "https://api.github.com/users/Shougo/received_events",
                "repos_url": "https://api.github.com/users/Shougo/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/Shougo/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Shougo/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/Shougo"
            }
        },
        {
            "author_association": "NONE",
            "body": "Seems like it...\r\n\r\n```\r\n  File \"C:\\Users\\Toqoz\\Documents\\code\\neovim-test\\something.py\", line 4\r\n    nvim = attach('child', argv=['C:\\Users\\Toqoz\\Documents\\code\\neovim-test\\Neovim2\\bin\\nvim.exe', \"--embed\"])\r\n                                                                                                 ^\r\nSyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \\UXXXXXXXX escape\r\n```\r\n\r\nI'm fairly sure it is finding `nvim.exe` since if you change the path you get a file not found error.",
            "created_at": "2022-04-12T09:59:39Z",
            "html_url": "https://github.com/neovim/pynvim/issues/505#issuecomment-1096483014",
            "id": 1096483014,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/505",
            "node_id": "IC_kwDOASpKTs5BWwDG",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1096483014/reactions"
            },
            "updated_at": "2022-04-12T09:59:39Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1096483014",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/6947819?v=4",
                "events_url": "https://api.github.com/users/Toqozz/events{/privacy}",
                "followers_url": "https://api.github.com/users/Toqozz/followers",
                "following_url": "https://api.github.com/users/Toqozz/following{/other_user}",
                "gists_url": "https://api.github.com/users/Toqozz/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/Toqozz",
                "id": 6947819,
                "login": "Toqozz",
                "node_id": "MDQ6VXNlcjY5NDc4MTk=",
                "organizations_url": "https://api.github.com/users/Toqozz/orgs",
                "received_events_url": "https://api.github.com/users/Toqozz/received_events",
                "repos_url": "https://api.github.com/users/Toqozz/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/Toqozz/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Toqozz/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/Toqozz"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "Hm.  You should enable log.",
            "created_at": "2022-04-12T12:10:21Z",
            "html_url": "https://github.com/neovim/pynvim/issues/505#issuecomment-1096644078",
            "id": 1096644078,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/505",
            "node_id": "IC_kwDOASpKTs5BXXXu",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1096644078/reactions"
            },
            "updated_at": "2022-04-12T12:10:21Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1096644078",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/41495?v=4",
                "events_url": "https://api.github.com/users/Shougo/events{/privacy}",
                "followers_url": "https://api.github.com/users/Shougo/followers",
                "following_url": "https://api.github.com/users/Shougo/following{/other_user}",
                "gists_url": "https://api.github.com/users/Shougo/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/Shougo",
                "id": 41495,
                "login": "Shougo",
                "node_id": "MDQ6VXNlcjQxNDk1",
                "organizations_url": "https://api.github.com/users/Shougo/orgs",
                "received_events_url": "https://api.github.com/users/Shougo/received_events",
                "repos_url": "https://api.github.com/users/Shougo/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/Shougo/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Shougo/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/Shougo"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "Reproduced it on neovim 0.7 Windows version.  It works on older neovim(0.5) or Linux neovim.\r\nSo I think something is changed.\r\n\r\nUnfortunately, pynvim is not maintained well.  neovim maintainers want to use Lua language instead.\r\n\r\nNote: if_python3 works well.",
            "created_at": "2022-04-17T03:28:56Z",
            "html_url": "https://github.com/neovim/pynvim/issues/505#issuecomment-1100795476",
            "id": 1100795476,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/505",
            "node_id": "IC_kwDOASpKTs5BnM5U",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1100795476/reactions"
            },
            "updated_at": "2022-04-17T03:36:16Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1100795476",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/41495?v=4",
                "events_url": "https://api.github.com/users/Shougo/events{/privacy}",
                "followers_url": "https://api.github.com/users/Shougo/followers",
                "following_url": "https://api.github.com/users/Shougo/following{/other_user}",
                "gists_url": "https://api.github.com/users/Shougo/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/Shougo",
                "id": 41495,
                "login": "Shougo",
                "node_id": "MDQ6VXNlcjQxNDk1",
                "organizations_url": "https://api.github.com/users/Shougo/orgs",
                "received_events_url": "https://api.github.com/users/Shougo/received_events",
                "repos_url": "https://api.github.com/users/Shougo/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/Shougo/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Shougo/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/Shougo"
            }
        },
        {
            "author_association": "NONE",
            "body": "Ah, thanks for that.  I'll look into getting something else working.",
            "created_at": "2022-04-17T07:11:32Z",
            "html_url": "https://github.com/neovim/pynvim/issues/505#issuecomment-1100819923",
            "id": 1100819923,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/505",
            "node_id": "IC_kwDOASpKTs5BnS3T",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1100819923/reactions"
            },
            "updated_at": "2022-04-17T07:11:32Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1100819923",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/6947819?v=4",
                "events_url": "https://api.github.com/users/Toqozz/events{/privacy}",
                "followers_url": "https://api.github.com/users/Toqozz/followers",
                "following_url": "https://api.github.com/users/Toqozz/following{/other_user}",
                "gists_url": "https://api.github.com/users/Toqozz/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/Toqozz",
                "id": 6947819,
                "login": "Toqozz",
                "node_id": "MDQ6VXNlcjY5NDc4MTk=",
                "organizations_url": "https://api.github.com/users/Toqozz/orgs",
                "received_events_url": "https://api.github.com/users/Toqozz/received_events",
                "repos_url": "https://api.github.com/users/Toqozz/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/Toqozz/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Toqozz/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/Toqozz"
            }
        },
        {
            "author_association": "NONE",
            "body": "neovim 0.4.4 was the latest version I was able to pynvim to work well with. For context, I'm on windows trying to use the ActualVim plugin on Sublime Text 4.",
            "created_at": "2022-05-18T20:40:24Z",
            "html_url": "https://github.com/neovim/pynvim/issues/505#issuecomment-1130515938",
            "id": 1130515938,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/505",
            "node_id": "IC_kwDOASpKTs5DYk3i",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1130515938/reactions"
            },
            "updated_at": "2022-05-18T20:40:24Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1130515938",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/7892414?v=4",
                "events_url": "https://api.github.com/users/MacKinley/events{/privacy}",
                "followers_url": "https://api.github.com/users/MacKinley/followers",
                "following_url": "https://api.github.com/users/MacKinley/following{/other_user}",
                "gists_url": "https://api.github.com/users/MacKinley/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/MacKinley",
                "id": 7892414,
                "login": "MacKinley",
                "node_id": "MDQ6VXNlcjc4OTI0MTQ=",
                "organizations_url": "https://api.github.com/users/MacKinley/orgs",
                "received_events_url": "https://api.github.com/users/MacKinley/received_events",
                "repos_url": "https://api.github.com/users/MacKinley/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/MacKinley/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/MacKinley/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/MacKinley"
            }
        },
        {
            "author_association": "NONE",
            "body": "Any updates on this? Tried it using Neovim 0.9.0 but still doesnt work..",
            "created_at": "2023-03-25T11:45:15Z",
            "html_url": "https://github.com/neovim/pynvim/issues/505#issuecomment-1483803191",
            "id": 1483803191,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/505",
            "node_id": "IC_kwDOASpKTs5YcQo3",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1483803191/reactions"
            },
            "updated_at": "2023-03-25T11:46:09Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1483803191",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/20560900?v=4",
                "events_url": "https://api.github.com/users/kuripa/events{/privacy}",
                "followers_url": "https://api.github.com/users/kuripa/followers",
                "following_url": "https://api.github.com/users/kuripa/following{/other_user}",
                "gists_url": "https://api.github.com/users/kuripa/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/kuripa",
                "id": 20560900,
                "login": "kuripa",
                "node_id": "MDQ6VXNlcjIwNTYwOTAw",
                "organizations_url": "https://api.github.com/users/kuripa/orgs",
                "received_events_url": "https://api.github.com/users/kuripa/received_events",
                "repos_url": "https://api.github.com/users/kuripa/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/kuripa/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/kuripa/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/kuripa"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Since CI (github actions) is online now, Windows CI jobs are showing similar failures (python 3.10, 3.11) : \r\n\r\n```\r\ntest/test_buffer.py::test_options ERROR                                  [ 10%]\r\n  Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x0000026941A645E0>\r\n  Traceback (most recent call last):\r\n    File \"C:\\hostedtoolcache\\windows\\Python\\3.11.4\\x64\\Lib\\asyncio\\base_subprocess.py\", line 126, in __del__\r\n      self.close()\r\n    File \"C:\\hostedtoolcache\\windows\\Python\\3.11.4\\x64\\Lib\\asyncio\\base_subprocess.py\", line 104, in close\r\n      proto.pipe.close()\r\n    File \"C:\\hostedtoolcache\\windows\\Python\\3.11.4\\x64\\Lib\\asyncio\\proactor_events.py\", line 109, in close\r\n      self._loop.call_soon(self._call_connection_lost, None)\r\n    File \"C:\\hostedtoolcache\\windows\\Python\\3.11.4\\x64\\Lib\\asyncio\\base_events.py\", line 761, in call_soon\r\n      self._check_closed()\r\n    File \"C:\\hostedtoolcache\\windows\\Python\\3.11.4\\x64\\Lib\\asyncio\\base_events.py\", line [51](https://github.com/neovim/pynvim/actions/runs/5559406058/jobs/10155486134#step:8:52)9, in _check_closed\r\n  Error:     raise RuntimeError('Event loop is closed')\r\n```",
            "created_at": "2023-07-15T11:56:44Z",
            "html_url": "https://github.com/neovim/pynvim/issues/505#issuecomment-1636746024",
            "id": 1636746024,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/505",
            "node_id": "IC_kwDOASpKTs5hjsMo",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1636746024/reactions"
            },
            "updated_at": "2023-07-15T11:56:44Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1636746024",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1359421?v=4",
                "events_url": "https://api.github.com/users/justinmk/events{/privacy}",
                "followers_url": "https://api.github.com/users/justinmk/followers",
                "following_url": "https://api.github.com/users/justinmk/following{/other_user}",
                "gists_url": "https://api.github.com/users/justinmk/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/justinmk",
                "id": 1359421,
                "login": "justinmk",
                "node_id": "MDQ6VXNlcjEzNTk0MjE=",
                "organizations_url": "https://api.github.com/users/justinmk/orgs",
                "received_events_url": "https://api.github.com/users/justinmk/received_events",
                "repos_url": "https://api.github.com/users/justinmk/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/justinmk/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/justinmk/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/justinmk"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "[neovim/neovim@`c86d5fa` (#11390)](https://github.com/neovim/neovim/pull/11390/commits/c86d5fa981b0651167f789aaff685b42cad7aaca) seems to be the culprit. See PR #543 for the fix.",
            "created_at": "2023-10-15T01:46:31Z",
            "html_url": "https://github.com/neovim/pynvim/issues/505#issuecomment-1763231271",
            "id": 1763231271,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/505",
            "node_id": "IC_kwDOASpKTs5pGMYn",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1763231271/reactions"
            },
            "updated_at": "2023-10-15T01:46:31Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1763231271",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1009873?v=4",
                "events_url": "https://api.github.com/users/wookayin/events{/privacy}",
                "followers_url": "https://api.github.com/users/wookayin/followers",
                "following_url": "https://api.github.com/users/wookayin/following{/other_user}",
                "gists_url": "https://api.github.com/users/wookayin/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/wookayin",
                "id": 1009873,
                "login": "wookayin",
                "node_id": "MDQ6VXNlcjEwMDk4NzM=",
                "organizations_url": "https://api.github.com/users/wookayin/orgs",
                "received_events_url": "https://api.github.com/users/wookayin/received_events",
                "repos_url": "https://api.github.com/users/wookayin/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/wookayin/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/wookayin/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/wookayin"
            }
        }
    ],
    "comments": 11,
    "comments_url": "https://api.github.com/repos/neovim/pynvim/issues/505/comments",
    "created_at": "2022-04-11T09:40:23Z",
    "events_url": "https://api.github.com/repos/neovim/pynvim/issues/505/events",
    "html_url": "https://github.com/neovim/pynvim/issues/505",
    "id": 1199696485,
    "labels": [
        {
            "color": "f9d0c4",
            "default": true,
            "description": null,
            "id": 97892276,
            "name": "bug",
            "node_id": "MDU6TGFiZWw5Nzg5MjI3Ng==",
            "url": "https://api.github.com/repos/neovim/pynvim/labels/bug"
        }
    ],
    "labels_url": "https://api.github.com/repos/neovim/pynvim/issues/505/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOASpKTs5Hgepl",
    "number": 505,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/neovim/pynvim/issues/505/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/pynvim",
    "state": "open",
    "state_reason": null,
    "timeline_url": "https://api.github.com/repos/neovim/pynvim/issues/505/timeline",
    "title": "OSError: EOF when trying to run example code on Windows",
    "updated_at": "2023-10-15T01:46:32Z",
    "url": "https://api.github.com/repos/neovim/pynvim/issues/505",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/6947819?v=4",
        "events_url": "https://api.github.com/users/Toqozz/events{/privacy}",
        "followers_url": "https://api.github.com/users/Toqozz/followers",
        "following_url": "https://api.github.com/users/Toqozz/following{/other_user}",
        "gists_url": "https://api.github.com/users/Toqozz/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/Toqozz",
        "id": 6947819,
        "login": "Toqozz",
        "node_id": "MDQ6VXNlcjY5NDc4MTk=",
        "organizations_url": "https://api.github.com/users/Toqozz/orgs",
        "received_events_url": "https://api.github.com/users/Toqozz/received_events",
        "repos_url": "https://api.github.com/users/Toqozz/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/Toqozz/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Toqozz/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/Toqozz"
    }
}