{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "\r\npip install pynvim fails trying to build greenlet.o\r\n\r\n`$ pip install pynvim`\r\n\r\nAttached is the log.  Below is the snippet showing the error \r\n\r\n`creating build/temp.macosx-11-arm64-cpython-39/src/greenlet\r\n      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -I/opt/homebrew/Cellar/python@3.9/3.9.13_1/envs/neovim/include -I/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c src/greenlet/greenlet.c -o build/temp.macosx-11-arm64-cpython-39/src/greenlet/greenlet.o\r\n      dyld: Library not loaded: @rpath/libclang-cpp.dylib\r\n        Referenced from: /opt/homebrew/bin/clang\r\n        Reason: image not found\r\n      error: command '/opt/homebrew/bin/clang' failed with exit code -6\r\n      [end of output]\r\n[log-install-pynvim.txt](https://github.com/neovim/pynvim/files/9247809/log-install-pynvim.txt)\r\n`",
    "closed_at": "2023-12-28T03:46:24Z",
    "comment_data": [
        {
            "author_association": "CONTRIBUTOR",
            "body": "It is not pynvim issue.\r\n\r\nhttps://github.com/neovim/pynvim/issues/502",
            "created_at": "2022-08-03T04:05:51Z",
            "html_url": "https://github.com/neovim/pynvim/issues/512#issuecomment-1203458275",
            "id": 1203458275,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/512",
            "node_id": "IC_kwDOASpKTs5Hu1Dj",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 1,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 2,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1203458275/reactions"
            },
            "updated_at": "2022-08-03T04:05:51Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1203458275",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/41495?v=4",
                "events_url": "https://api.github.com/users/Shougo/events{/privacy}",
                "followers_url": "https://api.github.com/users/Shougo/followers",
                "following_url": "https://api.github.com/users/Shougo/following{/other_user}",
                "gists_url": "https://api.github.com/users/Shougo/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/Shougo",
                "id": 41495,
                "login": "Shougo",
                "node_id": "MDQ6VXNlcjQxNDk1",
                "organizations_url": "https://api.github.com/users/Shougo/orgs",
                "received_events_url": "https://api.github.com/users/Shougo/received_events",
                "repos_url": "https://api.github.com/users/Shougo/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/Shougo/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Shougo/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/Shougo"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "On a M1 mac, one should use the following command to workaround the issue:\r\n\r\n`pip install --no-binary greenlet pynvim`\r\n\r\nSee also #473",
            "created_at": "2022-09-17T18:14:33Z",
            "html_url": "https://github.com/neovim/pynvim/issues/512#issuecomment-1250117756",
            "id": 1250117756,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/512",
            "node_id": "IC_kwDOASpKTs5Kg0h8",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 4,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 4,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1250117756/reactions"
            },
            "updated_at": "2022-09-17T18:16:23Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1250117756",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1009873?v=4",
                "events_url": "https://api.github.com/users/wookayin/events{/privacy}",
                "followers_url": "https://api.github.com/users/wookayin/followers",
                "following_url": "https://api.github.com/users/wookayin/following{/other_user}",
                "gists_url": "https://api.github.com/users/wookayin/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/wookayin",
                "id": 1009873,
                "login": "wookayin",
                "node_id": "MDQ6VXNlcjEwMDk4NzM=",
                "organizations_url": "https://api.github.com/users/wookayin/orgs",
                "received_events_url": "https://api.github.com/users/wookayin/received_events",
                "repos_url": "https://api.github.com/users/wookayin/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/wookayin/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/wookayin/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/wookayin"
            }
        },
        {
            "author_association": "NONE",
            "body": "I'm getting a similar error on my M1 Pro Macbook Pro:\r\n\r\n```\r\nstderr: Traceback (most recent call last):  File \"<string>\", line 1, in <module>  File \"/Users/jamie/opt/anaconda3/lib/python3.9/site-packages/neovim/__init__.py\", line 5, in <module>    import pynvim  File \"/Users/jamie/opt/anaconda3/lib/python3.9/site-packages/pynvim/__init__.py\", line 11, in <module>    from pynvim.msgpack_rpc import (ErrorResponse, child_session, socket_session,  File \"/Users/jamie/opt/anaconda3/lib/python3.9/site-packages/pynvim/msgpack_rpc/__init__.py\", line 10, in <module>    from pynvim.msgpack_rpc.session import ErrorResponse, Session  File \"/Users/jamie/opt/anaconda3/lib/python3.9/site-packages/pynvim/msgpack_rpc/session.py\", line 7, in <module>    import greenlet  File \"/Users/jamie/opt/anaconda3/lib/python3.9/site-packages/greenlet/__init__.py\", line 29, in <module>    from ._greenlet import _C_API # pylint:disable=no-name-in-moduleImportError: dlopen(/Users/jamie/opt/anaconda3/lib/python3.9/site-packages/greenlet/_greenlet.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '__ZSt20__throw_length_errorPKc'\r\n```\r\n\r\nwhen I check the file type of `_greenlet.cpython-39-darwin.so`, I get:\r\n\r\n```bash\r\n$ file ~/opt/anaconda3/lib/python3.9/site-packages/greenlet/_greenlet.cpython-39-darwin.so\r\n/Users/jamie/opt/anaconda3/lib/python3.9/site-packages/greenlet/_greenlet.cpython-39-darwin.so: Mach-O 64-bit bundle arm64\r\n```\r\n\r\nwhich indicates to me that greenlet is compiled for arm64\r\n\r\nI have tried different python versions (3.8, 3.9, 3.11) with the same result\r\n\r\nI have tried uninstalling and reinstalling `pynvim` and `greenlet` using the command\r\n\r\n```\r\npip uninstall pynvim greenlet\r\npip install --no-cache-dir --no-binary greenlet pynvim\r\n```\r\n\r\nbut the problem persists for me. I am running up-to-date macos 13.2, with xcode commandline developer tools installed.\r\n\r\nI am managing my python version using Anaconda, and I have neovim installed via homebrew.\r\n\r\n```\r\nnvim --version\r\nNVIM v0.8.2\r\nBuild type: Release\r\nLuaJIT 2.1.0-beta3\r\nCompiled by brew@Ventura-arm64.local\r\n\r\nFeatures: +acl +iconv +tui\r\nSee \":help feature-compile\"\r\n\r\n   system vimrc file: \"$VIM/sysinit.vim\"\r\n  fall-back for $VIM: \"/opt/homebrew/Cellar/neovim/0.8.2/share/nvim\"\r\n\r\nRun :checkhealth for more info\r\n```\r\n\r\n```zsh\r\npip show greenlet\r\nName: greenlet\r\nVersion: 2.0.1\r\nSummary: Lightweight in-process concurrent programming\r\nHome-page: https://greenlet.readthedocs.io/\r\nAuthor: Alexey Borzenkov\r\nAuthor-email: snaury@gmail.com\r\nLicense: MIT License\r\nLocation: /Users/jamie/opt/anaconda3/lib/python3.9/site-packages\r\nRequires:\r\nRequired-by: pynvim\r\n```\r\n\r\n```zsh\r\npip show pynvim\r\nName: pynvim\r\nVersion: 0.4.3\r\nSummary: Python client to neovim\r\nHome-page: http://github.com/neovim/pynvim\r\nAuthor: Thiago de Arruda\r\nAuthor-email: tpadilha84@gmail.com\r\nLicense: Apache\r\nLocation: /Users/jamie/opt/anaconda3/lib/python3.9/site-packages\r\nRequires: greenlet, msgpack\r\nRequired-by:\r\n```\r\n\r\nI have also tried setting `let g:python3_host_prog = '/Users/jamie/opt/anaconda3/bin/python'` with the same result.\r\n\r\nThe error comes up also when I open an python REPL and type `import pynvim`.\r\n\r\nDoes anybody have an idea to point me in the right direction?",
            "created_at": "2023-01-24T01:22:13Z",
            "html_url": "https://github.com/neovim/pynvim/issues/512#issuecomment-1401272907",
            "id": 1401272907,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/512",
            "node_id": "IC_kwDOASpKTs5ThbpL",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1401272907/reactions"
            },
            "updated_at": "2023-01-24T02:32:41Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1401272907",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1538657?v=4",
                "events_url": "https://api.github.com/users/sidequestboy/events{/privacy}",
                "followers_url": "https://api.github.com/users/sidequestboy/followers",
                "following_url": "https://api.github.com/users/sidequestboy/following{/other_user}",
                "gists_url": "https://api.github.com/users/sidequestboy/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/sidequestboy",
                "id": 1538657,
                "login": "sidequestboy",
                "node_id": "MDQ6VXNlcjE1Mzg2NTc=",
                "organizations_url": "https://api.github.com/users/sidequestboy/orgs",
                "received_events_url": "https://api.github.com/users/sidequestboy/received_events",
                "repos_url": "https://api.github.com/users/sidequestboy/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/sidequestboy/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/sidequestboy/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/sidequestboy"
            }
        },
        {
            "author_association": "NONE",
            "body": "I resolved my issue by ensuring `msgpack` and `greenlet` and `pip` were installed through anaconda. This was by:\r\n\r\n```\r\npip uninstall msgpack greenlet pynvim\r\n```\r\n```\r\nconda install pip\r\nCollecting package metadata (current_repodata.json): done\r\nSolving environment: /\r\nThe environment is inconsistent, please check the package plan carefully\r\nThe following packages are causing the inconsistency:\r\n\r\n  - defaults/osx-arm64::dask==2022.7.0=py39hca03da5_0\r\n  - defaults/osx-arm64::distributed==2022.7.0=py39hca03da5_0\r\n  - defaults/osx-arm64::anaconda==2022.10=py39_0\r\n  - defaults/noarch::intake==0.6.5=pyhd3eb1b0_0\r\n  - defaults/osx-arm64::sqlalchemy==1.4.39=py39h1a28f6b_0\r\n  - defaults/osx-arm64::datashader==0.14.1=py39hca03da5_0\r\ndone\r\n\r\n## Package Plan ##\r\n\r\n  environment location: /Users/jamie/opt/anaconda3\r\n\r\n  added / updated specs:\r\n    - pip\r\n\r\n\r\nThe following packages will be downloaded:\r\n\r\n    package                    |            build\r\n    ---------------------------|-----------------\r\n    _anaconda_depends-2022.10  |           py39_2          69 KB\r\n    anaconda-custom            |           py39_1           3 KB\r\n    certifi-2022.12.7          |   py39hca03da5_0         151 KB\r\n    greenlet-2.0.1             |   py39h313beb8_0         182 KB\r\n    pip-22.3.1                 |   py39hca03da5_0         2.7 MB\r\n    ------------------------------------------------------------\r\n                                           Total:         3.1 MB\r\n\r\nThe following NEW packages will be INSTALLED:\r\n\r\n  _anaconda_depends  pkgs/main/osx-arm64::_anaconda_depends-2022.10-py39_2\r\n  greenlet           pkgs/main/osx-arm64::greenlet-2.0.1-py39h313beb8_0\r\n  msgpack-python     pkgs/main/osx-arm64::msgpack-python-1.0.3-py39h525c30c_0\r\n\r\nThe following packages will be UPDATED:\r\n\r\n  ca-certificates                     2022.07.19-hca03da5_0 --> 2023.01.10-hca03da5_0\r\n  certifi                          2022.9.24-py39hca03da5_0 --> 2022.12.7-py39hca03da5_0\r\n  openssl                                 1.1.1q-h1a28f6b_0 --> 1.1.1s-h1a28f6b_0\r\n  pip                                 22.2.2-py39hca03da5_0 --> 22.3.1-py39hca03da5_0\r\n\r\nThe following packages will be DOWNGRADED:\r\n\r\n  anaconda                                   2022.10-py39_0 --> custom-py39_1\r\n\r\n\r\nProceed ([y]/n)? y\r\n```\r\n\r\nIt seems my issue has to do with ensuring that the compiler is the same between packages, and I guess python itself as well.\r\n\r\nThis stack overflow post helped put me in the right direction: https://stackoverflow.com/questions/35006614/what-does-symbol-not-found-expected-in-flat-namespace-actually-mean",
            "created_at": "2023-01-24T04:12:19Z",
            "html_url": "https://github.com/neovim/pynvim/issues/512#issuecomment-1401372049",
            "id": 1401372049,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/512",
            "node_id": "IC_kwDOASpKTs5Thz2R",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1401372049/reactions"
            },
            "updated_at": "2023-01-24T04:12:19Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1401372049",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1538657?v=4",
                "events_url": "https://api.github.com/users/sidequestboy/events{/privacy}",
                "followers_url": "https://api.github.com/users/sidequestboy/followers",
                "following_url": "https://api.github.com/users/sidequestboy/following{/other_user}",
                "gists_url": "https://api.github.com/users/sidequestboy/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/sidequestboy",
                "id": 1538657,
                "login": "sidequestboy",
                "node_id": "MDQ6VXNlcjE1Mzg2NTc=",
                "organizations_url": "https://api.github.com/users/sidequestboy/orgs",
                "received_events_url": "https://api.github.com/users/sidequestboy/received_events",
                "repos_url": "https://api.github.com/users/sidequestboy/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/sidequestboy/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/sidequestboy/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/sidequestboy"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "With greenlet 3.0+, all supported pythons have universal (x86_64 + arm64) wheel files, so we can close this now.",
            "created_at": "2023-12-28T03:46:24Z",
            "html_url": "https://github.com/neovim/pynvim/issues/512#issuecomment-1870795783",
            "id": 1870795783,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/512",
            "node_id": "IC_kwDOASpKTs5vghQH",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1870795783/reactions"
            },
            "updated_at": "2023-12-28T03:46:24Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1870795783",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1009873?v=4",
                "events_url": "https://api.github.com/users/wookayin/events{/privacy}",
                "followers_url": "https://api.github.com/users/wookayin/followers",
                "following_url": "https://api.github.com/users/wookayin/following{/other_user}",
                "gists_url": "https://api.github.com/users/wookayin/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/wookayin",
                "id": 1009873,
                "login": "wookayin",
                "node_id": "MDQ6VXNlcjEwMDk4NzM=",
                "organizations_url": "https://api.github.com/users/wookayin/orgs",
                "received_events_url": "https://api.github.com/users/wookayin/received_events",
                "repos_url": "https://api.github.com/users/wookayin/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/wookayin/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/wookayin/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/wookayin"
            }
        }
    ],
    "comments": 5,
    "comments_url": "https://api.github.com/repos/neovim/pynvim/issues/512/comments",
    "created_at": "2022-08-03T03:53:46Z",
    "events_url": "https://api.github.com/repos/neovim/pynvim/issues/512/events",
    "html_url": "https://github.com/neovim/pynvim/issues/512",
    "id": 1326642272,
    "labels": [],
    "labels_url": "https://api.github.com/repos/neovim/pynvim/issues/512/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOASpKTs5PEvRg",
    "number": 512,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/neovim/pynvim/issues/512/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/pynvim",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/neovim/pynvim/issues/512/timeline",
    "title": "pip install pynvim fails on macOS M1 trying to build greenlet.",
    "updated_at": "2023-12-28T03:46:45Z",
    "url": "https://api.github.com/repos/neovim/pynvim/issues/512",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/37938820?v=4",
        "events_url": "https://api.github.com/users/661020786/events{/privacy}",
        "followers_url": "https://api.github.com/users/661020786/followers",
        "following_url": "https://api.github.com/users/661020786/following{/other_user}",
        "gists_url": "https://api.github.com/users/661020786/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/661020786",
        "id": 37938820,
        "login": "661020786",
        "node_id": "MDQ6VXNlcjM3OTM4ODIw",
        "organizations_url": "https://api.github.com/users/661020786/orgs",
        "received_events_url": "https://api.github.com/users/661020786/received_events",
        "repos_url": "https://api.github.com/users/661020786/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/661020786/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/661020786/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/661020786"
    }
}