{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "Python 3.12 has removed support for the `imp` library and in particular for the `load_module` method of that package.\r\nThe `pynvim` package do not support Python 3.12 anymore.",
    "closed_at": null,
    "comment_data": [
        {
            "author_association": "MEMBER",
            "body": "This is fixed but the fix hasn't been released yet. https://github.com/neovim/pynvim/pull/534",
            "created_at": "2023-10-09T22:52:08Z",
            "html_url": "https://github.com/neovim/pynvim/issues/538#issuecomment-1754014194",
            "id": 1754014194,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/538",
            "node_id": "IC_kwDOASpKTs5ojCHy",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 5,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 5,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1754014194/reactions"
            },
            "updated_at": "2023-10-09T22:52:08Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1754014194",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1359421?v=4",
                "events_url": "https://api.github.com/users/justinmk/events{/privacy}",
                "followers_url": "https://api.github.com/users/justinmk/followers",
                "following_url": "https://api.github.com/users/justinmk/following{/other_user}",
                "gists_url": "https://api.github.com/users/justinmk/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/justinmk",
                "id": 1359421,
                "login": "justinmk",
                "node_id": "MDQ6VXNlcjEzNTk0MjE=",
                "organizations_url": "https://api.github.com/users/justinmk/orgs",
                "received_events_url": "https://api.github.com/users/justinmk/received_events",
                "repos_url": "https://api.github.com/users/justinmk/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/justinmk/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/justinmk/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/justinmk"
            }
        },
        {
            "author_association": "NONE",
            "body": "I have tested the master branch and indeed it solves my problem.",
            "created_at": "2023-10-10T05:11:17Z",
            "html_url": "https://github.com/neovim/pynvim/issues/538#issuecomment-1754396880",
            "id": 1754396880,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/538",
            "node_id": "IC_kwDOASpKTs5okfjQ",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1754396880/reactions"
            },
            "updated_at": "2023-10-10T05:11:17Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1754396880",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/160393?v=4",
                "events_url": "https://api.github.com/users/vds2212/events{/privacy}",
                "followers_url": "https://api.github.com/users/vds2212/followers",
                "following_url": "https://api.github.com/users/vds2212/following{/other_user}",
                "gists_url": "https://api.github.com/users/vds2212/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/vds2212",
                "id": 160393,
                "login": "vds2212",
                "node_id": "MDQ6VXNlcjE2MDM5Mw==",
                "organizations_url": "https://api.github.com/users/vds2212/orgs",
                "received_events_url": "https://api.github.com/users/vds2212/received_events",
                "repos_url": "https://api.github.com/users/vds2212/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/vds2212/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/vds2212/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/vds2212"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "Workaround: Until released, you can install the master version (0.5.0.devN):\r\n\r\n```\r\npip install 'pynvim @ git+https://github.com/neovim/pynvim'\r\n```",
            "created_at": "2023-10-13T04:05:59Z",
            "html_url": "https://github.com/neovim/pynvim/issues/538#issuecomment-1760735880",
            "id": 1760735880,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/538",
            "node_id": "IC_kwDOASpKTs5o8rKI",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 13,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 13,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1760735880/reactions"
            },
            "updated_at": "2023-11-20T22:49:39Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1760735880",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1009873?v=4",
                "events_url": "https://api.github.com/users/wookayin/events{/privacy}",
                "followers_url": "https://api.github.com/users/wookayin/followers",
                "following_url": "https://api.github.com/users/wookayin/following{/other_user}",
                "gists_url": "https://api.github.com/users/wookayin/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/wookayin",
                "id": 1009873,
                "login": "wookayin",
                "node_id": "MDQ6VXNlcjEwMDk4NzM=",
                "organizations_url": "https://api.github.com/users/wookayin/orgs",
                "received_events_url": "https://api.github.com/users/wookayin/received_events",
                "repos_url": "https://api.github.com/users/wookayin/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/wookayin/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/wookayin/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/wookayin"
            }
        },
        {
            "author_association": "NONE",
            "body": "> pip install 'pynvim @ git+https://github.com/neovim/pynvim'\r\n\r\nDoesn't work offline though. When will the fix be released?",
            "created_at": "2023-11-07T18:43:29Z",
            "html_url": "https://github.com/neovim/pynvim/issues/538#issuecomment-1799527328",
            "id": 1799527328,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/538",
            "node_id": "IC_kwDOASpKTs5rQpug",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 1,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1799527328/reactions"
            },
            "updated_at": "2023-11-07T18:43:29Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1799527328",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/6503931?v=4",
                "events_url": "https://api.github.com/users/smprather/events{/privacy}",
                "followers_url": "https://api.github.com/users/smprather/followers",
                "following_url": "https://api.github.com/users/smprather/following{/other_user}",
                "gists_url": "https://api.github.com/users/smprather/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/smprather",
                "id": 6503931,
                "login": "smprather",
                "node_id": "MDQ6VXNlcjY1MDM5MzE=",
                "organizations_url": "https://api.github.com/users/smprather/orgs",
                "received_events_url": "https://api.github.com/users/smprather/received_events",
                "repos_url": "https://api.github.com/users/smprather/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/smprather/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/smprather/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/smprather"
            }
        },
        {
            "author_association": "NONE",
            "body": "I'm sorry but I'm having trouble wiht this still. After launching neoivm with my virtualenv (called `pyenv`) \r\n```\r\n(pynvim) ~  > pip install 'pynvim @ git+https://github.com/neovim/pynvim'\r\n\r\npipi='pip install'\r\nCollecting pynvim@ git+https://github.com/neovim/pynvim\r\n  Cloning https://github.com/neovim/pynvim to /tmp/pip-install-n0z9krus/pynvim_b42a40d5d77c41389180500b9eb5e358\r\n  Running command git clone --filter=blob:none --quiet https://github.com/neovim/pynvim /tmp/pip-install-n0z9krus/pynvim_b42a40d5d77c41389180500b9eb5e358\r\n  Resolved https://github.com/neovim/pynvim to commit 169673714fd6d9f8bf53ed5ec55b9b01be5f560e\r\n  Installing build dependencies ... done\r\n  Getting requirements to build wheel ... done\r\n  Installing backend dependencies ... done\r\n  Preparing metadata (pyproject.toml) ... done\r\nRequirement already satisfied: msgpack>=0.5.0 in ./.pyenv/versions/pynvim/lib/python3.12/site-packages (from pynvim@ git+https://github.com/neovim/pynvim) (1.0.7)\r\nRequirement already satisfied: greenlet>=3.0 in ./.pyenv/versions/pynvim/lib/python3.12/site-packages (from pynvim@ git+https://github.com/neovim/pynvim) (3.0.1)\r\nBuilding wheels for collected packages: pynvim\r\n  Building wheel for pynvim (pyproject.toml) ... done\r\n  Created wheel for pynvim: filename=pynvim-0.5.0.dev0-py2.py3-none-any.whl size=45152 sha256=184ea39a7bbec6ab0c64a8e9b22384a8b27d5478683045894a61f7177d780299\r\n  Stored in directory: /tmp/pip-ephem-wheel-cache-5ia1gm3q/wheels/ed/e4/03/32c78f104e48c5c2f0353dcc1ef88cc58a4e8c3a21f41a3165\r\nSuccessfully built pynvim\r\nInstalling collected packages: pynvim\r\n  Attempting uninstall: pynvim\r\n    Found existing installation: pynvim 0.5.0.dev0\r\n    Uninstalling pynvim-0.5.0.dev0:\r\n      Successfully uninstalled pynvim-0.5.0.dev0\r\nSuccessfully installed pynvim-0.5.0.dev0                                                                                  /4.5s\r\n```\r\nLaunching nvim (Lunarvim, if it matters) with environment active:\r\n\r\n```\r\n:echo g:python_host_prog\r\n/home/<user>/.pyenv/version/pynvim/bin/python\r\n```\r\n\r\nRelevant section of `:checkhealth provider`:\r\n```\r\nPython 3 provider (optional) ~\r\n- pyenv: Path: /home/slack/.pyenv/libexec/pyenv\r\n- pyenv: Root: /home/slack/.pyenv\r\n- WARNING No Python executable found that can `import neovim`. Using the first available executable for diagnostics.\r\n- WARNING Could not load Python 3:\r\n  /home/slack/.pyenv/shims/python3 is Python <string>:1: DeprecationWarning: 'pkgutil.get_loader' is deprecated and slated for removal in Python 3.14; use importlib.util.find_spec() instead\r\n  3.12 and cannot provide Python 3.\r\n  /usr/bin/python3.10 does not have the \"neovim\" module.\r\n  python3.9 not found in search path or not executable.\r\n  python3.8 not found in search path or not executable.\r\n  python3.7 not found in search path or not executable.\r\n  /home/slack/.pyenv/shims/python is Python <string>:1: DeprecationWarning: 'pkgutil.get_loader' is deprecated and slated for removal in Python 3.14; use importlib.util.find_spec() instead\r\n  3.12 and cannot provide Python 3.\r\n  - ADVICE:\r\n    - See :help |provider-python| for more information.\r\n    - You may disable this provider (and warning) by adding `let g:loaded_python3_provider = 0` to your init.vim\r\n- Executable: Not found\r\n\r\nPython virtualenv ~\r\n- WARNING $VIRTUAL_ENV is set to: /home/slack/.pyenv/versions/3.12.0/envs/pynvim\r\n  And its /bin directory contains: python, python3, python3-config, python3.12, python3.12-config\r\n  But $PATH yields this python executable: /home/slack/.pyenv/versions/pynvim/bin/python\r\n  And $PATH in subshells yields this python executable: /home/slack/.pyenv/versions/pynvim/bin/python\r\n  And $PATH yields this python3 executable: /home/slack/.pyenv/versions/pynvim/bin/python3\r\n  And $PATH in subshells yields this python3 executable: /home/slack/.pyenv/versions/pynvim/bin/python3\r\n  And $PATH yields this python3-config executable: Usage: /home/slack/.pyenv/versions/pynvim/bin/python3-config --prefix|--exec-prefix|--includes|--libs|--cflags|--ldflags|--extension-suffix|--help|--abiflags|--configdir|--embed\r\n  \r\n  And $PATH in subshells yields this python3-config executable: Usage: /home/slack/.pyenv/versions/pynvim/bin/python3-config --prefix|--exec-prefix|--includes|--libs|--cflags|--ldflags|--extension-suffix|--help|--abiflags|--configdir|--embed\r\n  \r\n  And $PATH yields this python3.12 executable: /home/slack/.pyenv/versions/pynvim/bin/python3.12\r\n  And $PATH in subshells yields this python3.12 executable: /home/slack/.pyenv/versions/pynvim/bin/python3.12\r\n  And $PATH yields this python3.12-config executable: Usage: /home/slack/.pyenv/versions/pynvim/bin/python3.12-config --prefix|--exec-prefix|--includes|--libs|--cflags|--ldflags|--extension-suffix|--help|--abiflags|--configdir|--embed\r\n  \r\n  And $PATH in subshells yields this python3.12-config executable: Usage: /home/slack/.pyenv/versions/pynvim/bin/python3.12-config --prefix|--exec-prefix|--includes|--libs|--cflags|--ldflags|--extension-suffix|--help|--abiflags|--configdir|--embed\r\n  \r\n  So invoking Python may lead to unexpected results.\r\n  - ADVICE:\r\n    - $PATH ambiguities arise if the virtualenv is not properly activated prior to launching Nvim. Close Nvim, activate the virtualenv, check that invoking Python from the command line launches the correct one, then relaunch Nvim.\r\n    - $PATH ambiguities in subshells typically are caused by your shell config overriding the $PATH previously set by the virtualenv. Either prevent them from doing so, or use this workaround: https://vi.stackexchange.com/a/34996\r\n  ```\r\nI'm not sure what I might have done wrong to have it working for everyone else and not for me, but does someone have an idea of how to fix this? If I can provide any more info that would be helpful please let me know.",
            "created_at": "2023-11-22T16:33:06Z",
            "html_url": "https://github.com/neovim/pynvim/issues/538#issuecomment-1823101301",
            "id": 1823101301,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/538",
            "node_id": "IC_kwDOASpKTs5sqlF1",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1823101301/reactions"
            },
            "updated_at": "2023-11-22T16:33:06Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1823101301",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/54120437?v=4",
                "events_url": "https://api.github.com/users/slacksystem/events{/privacy}",
                "followers_url": "https://api.github.com/users/slacksystem/followers",
                "following_url": "https://api.github.com/users/slacksystem/following{/other_user}",
                "gists_url": "https://api.github.com/users/slacksystem/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/slacksystem",
                "id": 54120437,
                "login": "slacksystem",
                "node_id": "MDQ6VXNlcjU0MTIwNDM3",
                "organizations_url": "https://api.github.com/users/slacksystem/orgs",
                "received_events_url": "https://api.github.com/users/slacksystem/received_events",
                "repos_url": "https://api.github.com/users/slacksystem/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/slacksystem/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/slacksystem/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/slacksystem"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "@slacksystem you need to set `g:python3_host_prog`, not `g:python_host_prog`.\r\n\r\nAlso what's your neovim version? To support python 3.12, neovim 0.9.3 or higher is required. See neovim/neovim#25316\r\n\r\nIf neovim version is good, then in your case the python host (`/home/slack/.pyenv/shims/python3`) might have pynvim 0.4.3 installed. Verify your pynvim installation:\r\n```\r\n$ /home/slack/.pyenv/shims/python3 -c \"import pynvim; print(pynvim.__version__)\"\r\n0.5.0.dev0\r\n```\r\n\r\nI guess the `pip` command points to the wrong python. Make sure `which pip` points the same python3 in the activated virtualenv.\r\n```\r\n$ /home/slack/.pyenv/shims/python3 -m pip install 'pynvim @ git+https://github.com/neovim/pynvim'\r\n```",
            "created_at": "2023-11-25T13:50:11Z",
            "html_url": "https://github.com/neovim/pynvim/issues/538#issuecomment-1826325283",
            "id": 1826325283,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/538",
            "node_id": "IC_kwDOASpKTs5s24Mj",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1826325283/reactions"
            },
            "updated_at": "2023-11-25T13:51:59Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1826325283",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1009873?v=4",
                "events_url": "https://api.github.com/users/wookayin/events{/privacy}",
                "followers_url": "https://api.github.com/users/wookayin/followers",
                "following_url": "https://api.github.com/users/wookayin/following{/other_user}",
                "gists_url": "https://api.github.com/users/wookayin/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/wookayin",
                "id": 1009873,
                "login": "wookayin",
                "node_id": "MDQ6VXNlcjEwMDk4NzM=",
                "organizations_url": "https://api.github.com/users/wookayin/orgs",
                "received_events_url": "https://api.github.com/users/wookayin/received_events",
                "repos_url": "https://api.github.com/users/wookayin/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/wookayin/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/wookayin/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/wookayin"
            }
        }
    ],
    "comments": 6,
    "comments_url": "https://api.github.com/repos/neovim/pynvim/issues/538/comments",
    "created_at": "2023-10-09T17:12:00Z",
    "events_url": "https://api.github.com/repos/neovim/pynvim/issues/538/events",
    "html_url": "https://github.com/neovim/pynvim/issues/538",
    "id": 1933484611,
    "labels": [
        {
            "color": "f9d0c4",
            "default": true,
            "description": null,
            "id": 97892276,
            "name": "bug",
            "node_id": "MDU6TGFiZWw5Nzg5MjI3Ng==",
            "url": "https://api.github.com/repos/neovim/pynvim/labels/bug"
        }
    ],
    "labels_url": "https://api.github.com/repos/neovim/pynvim/issues/538/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOASpKTs5zPqJD",
    "number": 538,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 10,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 10,
        "url": "https://api.github.com/repos/neovim/pynvim/issues/538/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/pynvim",
    "state": "open",
    "state_reason": null,
    "timeline_url": "https://api.github.com/repos/neovim/pynvim/issues/538/timeline",
    "title": "Get error \"no module named imp\" with Python 3.12",
    "updated_at": "2023-11-25T13:51:59Z",
    "url": "https://api.github.com/repos/neovim/pynvim/issues/538",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/160393?v=4",
        "events_url": "https://api.github.com/users/vds2212/events{/privacy}",
        "followers_url": "https://api.github.com/users/vds2212/followers",
        "following_url": "https://api.github.com/users/vds2212/following{/other_user}",
        "gists_url": "https://api.github.com/users/vds2212/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/vds2212",
        "id": 160393,
        "login": "vds2212",
        "node_id": "MDQ6VXNlcjE2MDM5Mw==",
        "organizations_url": "https://api.github.com/users/vds2212/orgs",
        "received_events_url": "https://api.github.com/users/vds2212/received_events",
        "repos_url": "https://api.github.com/users/vds2212/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/vds2212/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/vds2212/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/vds2212"
    }
}